<?php
// $Id$: pi_selected_locations.module ou_mbg Exp $

/**
 * @file
 * Provides a "selected_measures2" node type.
 */

/**
 * Implementation of hook_node_info().
 */
function pi_selected_measures2_node_info() {
  // We return an array since a module can define multiple node types.
  // We're only defining one node type, type 'pi_selected_measures2'.
  return array(
    'pi_selected_measures2' => array(
      'name' => t('Selected measures'), // Required.
      'module' => 'pi_selected_measures2',  // Required.
      'description' => t('Select one or more measures for carrying out your inquiry'), // Required.
      'has_title' => FALSE,
      'title_label' => t('Selected Measures'),
      'has_body' => TRUE,
      'body_label' => t('Measures'),
      'locked' => TRUE
    )
  );
}

//Commented out as no longer used in Drupal 6. Previously only the hook_menu line was active MBG 09_08_11
/**
 * Implementation of hook_menu().
 */
//function pi_selected_measures2_menu($may_cache) {
//}

/**
 * Implementation of hook_perm().
 */
function pi_selected_measures2_perm() {
  return array('create pi_selected_measures2', 'edit own pi_selected_measures2');
}

/**
 * Implementation of hook_access().
 */
function pi_selected_measures2_access($op, $node) {
  global $user;

  if ($op == 'create') {
    return (user_access('create pi_selected_measures2'));
  }

  if ($op == 'update' || $op == 'delete') {
    return (user_access('edit own pi_selected_measures2'));
  }
}

/**
 * Implementation of hook_form().
 */
function pi_selected_measures2_form($node) {

  drupal_set_title(t('Pick measurements'));
  
  $type = node_get_types('type', $node);

  global $user;
  $uid = $user->uid;
  
  $audience_gid = find_student_group_gid($user);
  
  $results = db_query("SELECT nid,title FROM node WHERE type = 'pi_available_measures' AND status = '1'");
  $options = array();
  
  while ($result = db_fetch_array($results)) {
    $options[$result['nid']] = $result['title'];
  }

  $form['title'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->title_label),
    '#required' => FALSE,
    '#default_value' => check_plain($type->title_label),
    '#weight' => -5
  );
  $form['audience_gid'] = array(
    '#type' => 'hidden',
    '#title' => 'audience_gid',
    '#required' => FALSE,
    '#default_value' => $audience_gid
  );
  $form['body_filter']['body'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->body_label),
    '#required' => FALSE,
    '#default_value' => NULL,
    '#rows' => 5,
    '#weight' => -1
  );
  $form['selected_measures'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Available measurements'),
    '#required' => TRUE,
    '#multiple' => TRUE,
    '#default_value' => explode(",", $node->selected_measures),
    '#options' => $options,
    '#weight' => 5
  );
  
 $prefix = "<p>Pick which measurements you need. Click on the tabs on the right to find out more about these measurements.</p>";
  
  $form['#prefix'] = $prefix;

  return $form;
}

/**
 * Implementation of hook_validate().
 */
function pi_selected_measures2_validate($node) {
  // Enforce a minimum word length of 3.
  if (isset($node->selected_measures) && count($node->selected_measures) < 1) {
    $type = node_get_types('type', $node);
    form_set_error('selected_measures', t('Your @type is too short. You need at least one measure.', array('@type' => $type->name)));
  }
}

/**
 * Implementation of hook_insert().
 */
function pi_selected_measures2_insert($node) {
  pi_selected_measures_insert($node);
}


/**
 * Implementation of hook_update().
 */
function pi_selected_measures2_update($node) {
	pi_selected_measures_update($node);
}

/**
 * Implementation of hook_delete().
 */
function pi_selected_measures2_delete(&$node) {
	pi_selected_measures_delete($node);
}


/**
 * Implementation of hook_load().
 */
function pi_selected_measures2_load($node) {
  return pi_selected_measures_load($node);
}

/**
 * Implementation of hook_view().
 */
function pi_selected_measures2_view($node, $teaser = FALSE, $page = FALSE) {
  return pi_selected_measures_view($node, $teaser, $page);
}

