<?php

/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function google_maps_measure_install() {
  pi_available_measures_plugins_register_measure_type('_googlemap', 'google_maps_measure');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function google_maps_measure_uninstall() {
  pi_available_measures_plugins_forget_measure_type('_googlemap');
}

