<?php

// $Id: pi_read_information.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_read_information" node type
 */

/**
 * Implementation of hook_node_info().
 */
function pi_read_information_node_info() {

	return array(
			'pi_read_information' => array(
					'name' => t('Inquiry information'), // Required.
					'module' => 'pi_read_information', // Required.
					'description' => t('Read information about a topic'), // Required.
					'has_title' => TRUE,
					'title_label' => t('Information'),
					'has_body' => TRUE,
					'body_label' => t('Information'),
					'locked' => TRUE)
	);
}

/**
 * Implementation of hook_perm().
 */
function pi_read_information_perm() {
	
}

/**
 * Implementation of hook_access().
 */
function pi_read_information_access($op, $node, $account) {
	return FALSE;
}

/**
 * Implementation of hook_form().
 */
function pi_read_information_form(&$node) {

	// Get metadata for this node type
	// (we use it for labeling title and body fields).
	// We defined this in pi_read_information_node_info().
	$type = node_get_types('type', $node);

	$form['title'] = array(
			'#type' => 'hidden',
			'#title' => check_plain($type->title_label),
			'#required' => FALSE,
			'#default_value' => $type->title_label,
			'#weight' => -5
	);

	$form['body_filter']['body'] = array(
			'#type' => 'textarea',
			'#title' => t('Notes'),
			'#required' => FALSE,
			'#default_value' => $node->body,
			'#description' => t('Type your group notes into the above box and click on the Save button when you are finished'),
			'#resizable' => TRUE,
			'#rows' => 8,
			'#cols' => 40,
			'#weight' => -2
	);

	return $form;
}

/**
 * Implementation of hook_view().
 */
function pi_read_information_view($node, $teaser = FALSE, $page = FALSE) {
	$node = node_prepare($node, $teaser);
	return $node;
}

function pi_read_information_show_edit_link() {
	return FALSE;
}

function pi_read_information_display_content_in_activity($node) {
	return array(
			'mode' => 'singleblock',
			'content' => $node ? $node->body : FALSE,
	);
}
