<?php
// $Id: quiz_directions.module,v 1.1.2.1 2009/05/08 19:52:28 mbutcher Exp $

/**
 * The main file for quiz_directions.
 *
 * Directions are implemented as a question type. However, they do not affect the score.
 * @file
 */

/**
 * Implementation of hook_help().
 */
function quiz_directions_help($path, $args) {
  if ($path == 'admin/help#quiz_directions') {
    return t('Provides directions which can be inserted alongside questions in a quiz.');
  }
}

/**
 * Implementation of hook_quiz_question_info().
 */
function quiz_directions_quiz_question_info() { 
  return array(
    'quiz_directions' => array(
      'name' => 'Quiz directions',
      'description' => 'Quiz directions allow you to drop in directions anywhere in a quiz. You can also use them to insert a confirmation step at the end of the quiz.',
      'question provider' => 'QuizDirectionsQuestion',
      'response provider' => 'QuizDirectionsResponse',
      'module' => 'quiz_question', // All wrapper functions are in that module.
    ),
  );
}

/**
 * Implementation of hook_autoload_info().
 */
function quiz_directions_autoload_info() {
  return array(
    'QuizDirectionsQuestion' => array('file' => 'quiz_directions.classes.inc'),
    'QuizDirectionsResponse' => array('file' => 'quiz_directions.classes.inc'),
  );
}