<?php
// $Id: pi.module,v 0.1 2009/05/10 09:00:00 tdc5 $

/**
 * @file
 * Enables the use of the PI activity guide.
 */

/**
 * Implementation of hook_init().
 */
function pi_ag_init()
{
	drupal_add_css(drupal_get_path('module', 'pi_ag') .'/pi_ag.css');
	drupal_add_js(drupal_get_path('module', 'pi_ag') .'/pi_ag.js');
}

 // ----------------------------------------------------------------------------------
 
function pi_ag_build_link($first, $second, $third, $inquiry_id = 0, $stage_id = 0, $phase_id = 0, $activity_id = 0)
{
	if (! $activity_id) {
		return t($first . "/" . $second . "/" . $third . "/" . $inquiry_id . "/" . $stage_id . "/" . $phase_id);
	}
	else {
		return t($first . "/" . $second . "/" . $third . "/" . $inquiry_id . "/" . $stage_id . "/" . $phase_id . "/" . $activity_id);
	}
}
 
 function pi_ag_build_home_link($inquiry_id, $stage_id)
 {
	if (!$inquiry_id) {
		$db_result = get_inquiries_of_user($uid);
		$latest_inquiry = db_fetch_object($db_result);
		$inquiry_id = $latest_inquiry->inquiry_id;
	}
	return t("home///$inquiry_id/$stage_id/");
	//return t("home///" . $inquiry_id . "/" . $stage_id . "/" . $phase_id . "/" . $activity_id);
}

function pi_ag_build_activity_link_old($inquiry_id, $stage_id, $phase_id, $activity_id, $uid) {
	
	$image_path = "images/";
	$status_image = array();
	$status_image["start"] = "creatable.png";
	$status_image["edit"] = "editable.png";
	$status_image["view"] = "viewable.png";
	$status_image["unavailable"] = "unavailable.png";
	
	$loaded_activity = load_activity($activity_id);
	$params = $loaded_activity->parameters;
					
	//get node_function and visible_status for inuiqry, activity, uid, gid
	$visible_status = get_visible_status_of_activity ($inquiry_id, $activity_id, $uid);
	$node_function = get_node_function_of_activity ($inquiry_id, $activity_id, $uid);
	
	switch ($loaded_activity->destination) {
    case "self":
		$destination = "";
        break;
    case "phase":
		$destination = t("destination=" . pi_ag_build_link("phase", $phase_id, "view", $inquiry_id, $stage_id, $phase_id,$activity_id));
        break;
    default:
		$destination = t("destination=" . pi_ag_build_home_link($inquiry_id, $stage_id));
        break;
	}
	
	$teacher_gid = check_teacher_activity_for_inquiry_activity_user ($inquiry_id, $activity_id, $uid);
	
	if ($visible_status == "unavailable") {
		$output = t("<img class='ag-icon' src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>");
	}
	elseif ($node_function == "add") {
		$link = pi_ag_build_link("node", $node_function, str_replace("_", "-", $loaded_activity->node_type), $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}	
		$output = l(t("<img class='ag-icon' src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>"), $link,  array('html' => true, 'query' => $destination));
	}
	else {
		$nid = get_nid_for_inquiry_activity_and_user($inquiry_id, $activity_id, $uid);
		//$nid = get_nid_for_inquiry_activity_and_user(1, 3, 1);
		$link = pi_ag_build_link("node", $nid, $node_function, $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}
		$output = l(t("<img class='ag-icon' src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>"), $link,  array('html' => true, 'query' => $destination));
	}
	
	return $output;
}

function pi_ag_build_activity_link($inquiry_id, $stage_id, $phase_id, $activity_id, $uid) {
	
	$image_path = "images/";
	$status_image = array();
	$status_image["start"] = "creatable.png";
	$status_image["edit"] = "editable.png";
	$status_image["view"] = "viewable.png";
	$status_image["unavailable"] = "unavailable.png";
	
	$loaded_activity = load_activity($activity_id);
	$params = $loaded_activity->parameters;
					
	//get node_function and visible_status for inuiqry, activity, uid, gid
	$visible_status = get_visible_status_of_activity ($inquiry_id, $activity_id, $uid);
	$node_function = get_node_function_of_activity ($inquiry_id, $activity_id, $uid);
	
	switch ($loaded_activity->destination) {
    case "self":
		$destination = "";
        break;
    case "phase":
		$destination = t("destination=" . pi_ag_build_link("phase", $phase_id, "view", $inquiry_id, $stage_id, $phase_id,$activity_id));
        break;
    default:
		$destination = t("destination=" . pi_ag_build_home_link($inquiry_id, $stage_id));
        break;
	}
	
	$teacher_gid = check_teacher_activity_for_inquiry_activity_user ($inquiry_id, $activity_id, $uid);
	
  $activity_name_text = $loaded_activity->name . teacher_only_flag($teacher_gid);
    
	if ($visible_status == "unavailable") {
		$output = array('data' =>  t($activity_name_text), 'class' => 'ag-activity-unavailable');
	}
	elseif ($node_function == "add") {
		$link = pi_ag_build_link("node", $node_function, str_replace("_", "-", $loaded_activity->node_type), $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}	
    $activity_name_link = l($activity_name_text, $link,  array('html' => true, 'query' => $destination));
		$output = array('data' =>  t($activity_name_link), 'class' => 'ag-activity-add');
	}

	else {
		$nid = get_nid_for_inquiry_activity_and_user($inquiry_id, $activity_id, $uid);
		//$nid = get_nid_for_inquiry_activity_and_user(1, 3, 1);
		$link = pi_ag_build_link("node", $nid, $node_function, $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}
    	$activity_name_link = l($activity_name_text, $link,  array('html' => true, 'query' => $destination));
    	if ($visible_status == 'edit') {
			$output = array('data' => t($activity_name_link), 'class' => 'ag-activity-edit');
		}
		else {
			$output = array('data' => t($activity_name_link), 'class' => 'ag-activity-view');
		}
	};
	
	return $output;
}
