<?php

// $Id: pi_available_measures.module,v 1.1 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "available measurements" node type
 */

/**
 * Implementation of pi_available_measures_node_info().
 */
function pi_available_measures_node_info() {
	return array(
			'pi_available_measures' => array(
					'name' => t('Inquiry available measures'), // Required.
					'module' => 'pi_available_measures', // Required.
					'description' => t('What are you going to measure?'), // Required.
					'has_title' => TRUE,
					'title_label' => t('Name'),
					'has_body' => TRUE,
					'body_label' => t('Description'),
					'min_word_count' => 2,
					'locked' => TRUE
			)
	);
}

/**
 * Implementation of pi_available_measures_perm().
 */
function pi_available_measures_perm() {
	
}

/**
 * Implementation of pi_available_measures_access().
 */
function pi_available_measures_access($op, $node, $account) {
	return TRUE;
	global $user;
	$uid = $user->uid;

	/* FIX (eloy) allow delete if we are in Creator */
	if (arg(0) == 'creator') {
		return $uid == $node->uid;
	} else {
		$details = get_inquiry_details_from_current_path();
		if (is_numeric($details->activity_id)) {

			if ($op == 'create') {
				return pi_activity_check_node_function($details->activity_id, $user->uid, 'add');
			}
			if ($op == 'update') {
				return pi_activity_check_node_function($details->activity_id, $user->uid, 'edit');
			}
			if ($op == 'delete') {
				if (arg(0) == 'node' && arg(2) == 'delete') {
					//get inquiry for session id and activity
					$nid = arg(1);
					$activity_id = pi_activity_get_activity_nid_for_content_nid($nid);
					$inquiry_id = pi_activity_get_inquiry_nid($activity_id);
					if ($inquiry_id && $activity_id) {
						return pi_activity_check_node_function($activity_id, $uid, 'edit');
					} else {
						return FALSE;
					}
				} else {
					return pi_activity_check_node_function($details->activity_id, $user->uid, 'edit');
				}
			}
		}
	}
}

/**
 * Implementation of pi_available_measures_form().
 */
function pi_available_measures_form(&$measure, $form_state) {
	$form = array();
	ahah_helper_register($form, $form_state);
	
	if (arg(0) === 'activity') {
		$form['current_activity_nid'] = array(
				'#type' => 'hidden',
				'#default_value' => arg(1),
		);
	} else {
		$current_activity_nid = $form_state['values']['current_activity_nid'];
		$form['current_activity_nid'] = array(
				'#type' => 'hidden',
				'#default_value' => $current_activity_nid,
		);
		pi_inquiry_groupings_alter_access_data_set_activity($current_activity_nid);
	}
	
	$data_activities = pi_sort_data_get_activities();
	$data_activity_options = array(0 => t('- Select activity'));
	foreach ($data_activities as $activity_data) {
		$data_activity_options[$activity_data['node']->nid] = check_plain($activity_data['node']->title);
	}

	//function inquiry_creator_measure_form(&$form_state, $design, $activity, $measure) {
	//nquire_commons_form_set_default_link_action($form, 'submit');

	$data_activity_nid = nquire_commons_form_node_default_value($measure, 'activity_nid', $form_state, 'activity_nid', 0);
	$form['activity_nid'] = array(
			'#type' => 'select',
			'#title' => t('Data gathering activity'),
			'#description' => t('Select the data activity in which the measure will be used.'),
			'#default_value' => $data_activity_nid,
			'#required' => TRUE,
			'#options' => $data_activity_options,
			'#ahah' => array(
					'path' => ahah_helper_path(array('measures_activity_dependent_section')),
					'wrapper' => 'measures_activity_dependent_section',
					'method' => 'replace',
					'effect' => 'fade',
			),
	);

	nquire_commons_create_form_wrapped_section($form, 'measures_activity_dependent_section');
	$activity_dependent_form = &$form['measures_activity_dependent_section']['wrapped_content'];

	$data_activity = node_load($data_activity_nid);
	if ($data_activity) {
		$tool = nquire_commons_read_data_value($data_activity->data, 'tool.type', 'none');
		if ('tool' !== 'none') {
			$activity_dependent_form['tool'] = array(
					'#value' => '<p>' . t('@activity uses the following instrument to collect data: @tool.', array(
							'@activity' => $data_activity->title,
							'@tool' => inquiry_available_features_name('tool', $tool),
					)) . '</p>',
			);
		}

		$title = nquire_commons_form_node_default_value($measure, 'title', $form_state, 'title', '');
		$description = nquire_commons_form_node_default_value($measure, 'body', $form_state, 'description', '');
		$type = nquire_commons_form_node_default_value($measure, 'measure_type', $form_state, 'measure_type', '');
		$measure_or_type = $measure && $measure->measure_type == $type ? $measure : $type;

		$activity_dependent_form['title'] = array(
				'#type' => 'textfield',
				'#title' => t('Measure name'),
				'#description' => t('Write here the name that will identify the measure.'),
				'#required' => TRUE,
				'#default_value' => $title,
		);

		$activity_dependent_form['description'] = array(
				'#type' => 'textarea',
				'#title' => t('Measure description'),
				'#description' => t('Write here the description of the measure. This could include, for instance, an explanation of how to use this measure.'),
				'#default_value' => $description,
				'#required' => FALSE
		);

		$options = inquiry_available_features_list_measures_for_tool($tool);

		if (!isset($options[$type])) {
			if ($type === '') {
				$options[$type] = t('- Select a measure type');
			} else {
				$required_tool = inquiry_available_features_measure_required_tool($type);
				$options[$type] = inquiry_available_features_name('measure', $type) . t(' (unavailable as @tool is not used)', array('@tool' => inquiry_available_features_name('tool', $required_tool)));
			}
		}

		ksort($options);


		$activity_dependent_form['measure_type'] = array(
				'#type' => 'select',
				'#title' => t('Measure type'),
				'#description' => t('Select the measure type. Some measure types are only available when certain intruments are used to collect data.'),
				'#default_value' => $type,
				'#required' => TRUE,
				'#options' => $options,
				'#ahah' => array(
						'path' => ahah_helper_path(array('measures_activity_dependent_section', 'wrapped_content', 'measures_type_dependent_section')),
						'wrapper' => 'measures_type_dependent_section',
						'method' => 'replace',
						'effect' => 'fade',
				),
		);

		nquire_commons_create_form_wrapped_section($activity_dependent_form, 'measures_type_dependent_section');
		$type_dependent_form = &$activity_dependent_form['measures_type_dependent_section']['wrapped_content'];

		$type_dependent_form['#tree'] = TRUE;

		$type_dependent_form['help'] = array(
				'#value' => '<p><b>' . check_plain(inquiry_available_features_invoke('measure', 'description', $type)) . '</b></p>',
		);

		inquiry_available_features_invoke('measure', 'form', $measure_or_type, $type_dependent_form, $form_state);
	}

	return $form;
}
function pi_available_measures_form_pi_available_measures_node_form_alter(&$form, &$form_state) {
	$form['buttons']['submit']['#submit'][] = '_pi_available_measures_form_redirect';
}

function _pi_available_measures_form_redirect($form, &$form_state) {
	$measure_activity_id = $form_state['values']['current_activity_nid'];
	$measure_activity = node_load($measure_activity_id);
	$form_state['redirect'] = 'activity/' . $measure_activity->parent_activity;
}

/**
 * Implementation of pi_available_measures_valiate().
 */
function pi_available_measures_validate($node, &$form, &$form_state) {
	//$type = $form['values']['measure_type'];
	//inquiry_available_features_invoke('measure', 'form_validate', $type, $node, $form);
}

/**
 * hook_insert() for available_measures: adds image node if needed
 */
function _pi_available_measures_form_process(&$node) {
	inquiry_available_features_invoke('measure', 'form_process', $node, $node->wrapped_content);
}

function pi_available_measures_insert($node) {
	if ($node->current_activity_nid) {
		_pi_available_measures_form_process($node);
	}

	db_query("INSERT INTO {pi_available_measures} (nid, vid, mandatory, script_measure, measure_type, data, activity_nid) VALUES (%d, %d, %d, %d, '%s', '%s', %d)", $node->nid, $node->vid, $node->mandatory ? 1 : 0, $node->script_measure ? 1 : 0, $node->measure_type, $node->data, $node->activity_nid);

	if ($node->current_activity_nid) {
		$activity = node_load($node->current_activity_nid);
	//	drupal_goto('activity/' . $activity->parent_activity);
	}
}

/**
 * Implementation of pi_available_measures_update().
 */
function pi_available_measures_update($node) {
	if ($node->revision) {
		pi_available_measures_insert($node);
	} else {
		if ($node->current_activity_nid) {
			_pi_available_measures_form_process($node);
		}
		db_query("UPDATE {pi_available_measures} SET mandatory='%d', script_measure='%d', measure_type='%s', data='%s', activity_nid='%d' WHERE vid=%d", $node->mandatory ? 1 : 0, $node->script_measure ? 1 : 0, $node->measure_type, $node->data, $node->activity_nid, $node->vid);
		if ($node->current_activity_nid) {
			$activity = node_load($node['current_activity_nid']);
		//	drupal_goto('activity/' . $activity->parent_activity);
		}
	}
}

/**
 * Implementation of pi_available_measures_delete().
 */
function pi_available_measures_delete(&$node) {
	// Delete the related information we were saving for this node.
	db_query('DELETE FROM {pi_available_measures} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of pi_available_measures_load().
 */
function pi_available_measures_load($node) {
	// drupal_add_js('misc/collapse.js');
	return db_fetch_object(db_query('SELECT * FROM {pi_available_measures} WHERE vid = %d', $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_available_measures_view($node, $teaser = FALSE, $page = FALSE) {
	global $user;
	$node_details = get_inquiry_details_from_current_path();

	// Use Drupal's default node view.
	$node = node_prepare($node, $teaser);
	if (is_numeric($node_details->activity_id)) {
		$current_activity = node_load($node_details->activity_id);
		if ($current_activity->title) {
			drupal_set_title(check_plain($current_activity->title));
		}
	}

	$filter_node = pi_measure_filter_get_measure_filter_for_inquiry($node_details->inquiry_id);

	// Load the measure data into a list, to save time stick them in a master list:
	// "switch" method", "value" method and text description
	$measure_parameters_switch_values_and_description_list = array(
			array('symbol_test', 'symbol', 'Symbol / short-name'),
			array('units_test', 'units', 'Units'),
			array('units_short_test', 'units_short', 'Units symbol / short name'),
			array('data_type_test', 'data_type', 'Data type'),
			array('list_options_test', 'list_options', 'Menu options'),
			array('content_options_test', 'content_options', 'Content options'),
			array('measurement_device_name_test', 'measurement_device_name', 'Device name'),
			array('measurement_device_description_test', 'measurement_device_description', 'Device description'),
	);

	$measure_parameters_defined = array();
	foreach ($measure_parameters_switch_values_and_description_list as $parameter) {
		$switch = $parameter[0];

		// See if the parameter is used
		if ($filter_node->$switch) {
			$value = $parameter[1];
			if (strlen($node->$value) > 0) {
				$description = $parameter[2];
				// Handle the special types or default to a standard format
				switch ($value) {
					case 'data_type':
						$processed_value = ucwords($node->$value);
						break;
					case 'list_options':
						$raw_values = explode("\n", $node->$value);
						$processed_value = array();
						foreach ($raw_values as $raw_value) {
							$processed_value[] = trim($raw_value);
						}
						break;
					default:
						$processed_value = $node->$value;
				}
				$measure_parameters_defined[$value] = array(
						'title' => $description,
						'value' => $processed_value
				);
			}
		}
	}
	$measure_parameters_defined['field_type'] = array(
			'title' => t('Field type'),
			'value' => $node->field_type
	);

	if ($teaser) {
		$node->content['pi_available_measures_teaser'] = array(
				'#value' => theme('pi_available_measures_teaser', $node, $measure_parameters_defined),
				'#weight' => 0,
				'#style' => 'margin-top:2px;'
		);
		$node->content['body']['#value'] = '';
	} else {
		if ($node->image_id) {
			$node->content['pi_available_measures_image'] = array(
					'#value' => theme('pi_available_measures_image', $node->image_id, $teaser),
					'#weight' => -1
			);
		}
		$node->content['pi_available_measures'] = array(
				'#value' => theme('pi_available_measures', $node, $measure_parameters_defined),
				'#weight' => 1
		);
	}
	return $node;
}

/**
 * hook_theme() for pi_available_measures
 * @return array of theme data as per drupal 6 api
 */
function pi_available_measures_theme() {
	return array(
			'pi_available_measures' => array(
					'arguments' => array('node', 'measures_parameters'),
			),
			'pi_available_measures_teaser' => array(
					'arguments' => array('node', 'measures_parameters'),
			),
			'pi_available_measures_image' => array(
					'arguments' => array('image_node_nid', 'teaser')
			)
	);
}

/**
 * Theme function for pi_acailale_measures
 * @param object(node->pi_available_measures) $node
 * @param bool $teaser whethere to render teaser or full view
 * @param array $measures_parameters array of parameter name, value and description to show
 * @return string HTML output
 */
function theme_pi_available_measures($node, $measures_parameters) {

	$output = '';

	unset($measures_parameters['field_type']);
	// For the long list of parameters, iterate through them and process any exceptions here,
	// otherwise use a standard format.
	foreach ($measures_parameters as $parameter_type => $parameter) {
		$print_title = $parameter['title'];
		switch ($parameter_type) {
			case 'data_type':
				$print_value = check_plain(ucwords($parameter['value']));
				break;
			case 'list_options':
				$print_value = theme('item_list', $parameter['value']);
				break;
			case 'content_options':
				$print_value = theme('item_list', get_node_teasers_by_type($measures_parameters['content_options']['value']));

				break;
			default:
				$print_value = check_plain($parameter['value']);
		}
		$output .= "<p><span class='heading'>" . check_plain($print_title) . "</span>:&nbsp;" . $print_value . "</p>";
	}
	return $output;
}

/**
 * Theme function for pi_acailale_measures
 * @param object(node->pi_available_measures) $node
 * @param bool $teaser weather to render teaser or full view
 * @param array $measures_parameters array of parameter name, value and description to show
 * @return string HTML output
 */
function theme_pi_available_measures_teaser($node, $measures_parameters) {

	$output = '';

	switch ($measures_parameters['field_type']['value']) {
		case 'upload-file':
			$output .= t('Upload a file');
			unset($measures_parameters['data_type']);
			break;
		case 'upload-image':
			$output .= t('Upload an image');
			unset($measures_parameters['data_type']);
			break;
	}
	unset($measures_parameters['field_type']);
	if (array_key_exists('data_type', $measures_parameters)) {
		switch (strtolower($measures_parameters['data_type']['value'])) {
			case 'text':
				switch ($measures_parameters['field_type']) {
					case 'upload-file':
					case 'upload-image':
						$output .= t('Upload');
						break;
					default:
						$output .= t('Text');
				}
				unset($measures_parameters['data_type']);
				break;
			case 'numeric':
				$output .= t('A number');
				unset($measures_parameters['data_type']);
				break;
			case 'menu':
				$title = t('Choose from');
				if ($measures_parameters['list_options']['value']) {
					$value = implode(', ', $measures_parameters['list_options']['value']);
					$output .= $title . ":&nbsp;" . check_plain($value);
				} elseif ($measures_parameters['content_options']['value']) {
					$value = implode(', ', get_node_titles_by_type($measures_parameters['content_options']['value']));

					$output .= $title . ":&nbsp;" . check_plain($value);
				}
				unset($measures_parameters['data_type']);
				unset($measures_parameters['list_options']);
				break;
		}
	}
	if (isset($measures_parameters['units'])) {
		$title = t('measured in');
		$value = $measures_parameters['units']['value'];
		$output .= " " . $title . " " . check_plain($value);
		unset($measures_parameters['units']);
	}

	if (isset($measures_parameters['units_short'])) {
		$value = $measures_parameters['units_short']['value'];
		$output .= " (" . check_plain($value) . ")";
		unset($measures_parameters['units_short']);
	}

	if (isset($measures_parameters['measurement_device_name'])) {
		$title = t('using');
		$value = $measures_parameters['measurement_device_name']['value'];
		$output .= " " . $title . " the " . check_plain($value);
		unset($measures_parameters['measurement_device_name']);
	}

	return $output . ".";
}

function get_node_nids_by_type($content_type) {
	$nids = array();
	$query = "SELECT nid, title FROM {node} WHERE type = '%s' ORDER BY nid ASC";
	$result = db_query($query, $content_type);
	while ($content_node = db_fetch_object($result)) {
		$nids[] = $content_node->nid;
	}
	return $nids;
}

function get_node_titles_by_type($content_type) {
	$titles = array();
	$query = "SELECT nid, title FROM {node} WHERE type = '%s' ORDER BY nid ASC";
	$result = db_query($query, $content_type);
	while ($content_node = db_fetch_object($result)) {
		$titles[] = $content_node->title;
	}
	return $titles;
}

function get_node_teasers_by_type($content_type) {
	$titles = array();
	$query = "SELECT nid, title FROM {node} WHERE type = '%s' ORDER BY nid ASC";
	$result = db_query($query, $content_type);
	while ($content_node = db_fetch_object($result)) {
		// $titles[] = t($content_node->title) . node_view(node_load($content_node->nid), TRUE, TRUE);
		$titles[] = node_view(node_load($content_node->nid), TRUE, FALSE);
	}
	return $titles;
}

/**
 * Theme function to place an image in a measure page
 * @param unknown_type $image_node_nid
 * @param unknown_type $teaser
 */
function theme_pi_available_measures_image($image_node_nid, $teaser) {
	$output = '';
	// If the measure had an image attached, deal with that here so it can float left at the top of the page
	$image_node = node_load($image_node_nid);
	$output .= '<div style="float: right; clear: right; padding: 10px 0 10px 10px;">';
	if ($image_node->type == 'image') {
		$output .= theme('image_teaser', $image_node, NULL);
	} else {
		$output .= t("Image ") . check_plain($image_node_nid) . t(' not found.');
	}
	$output .= '</div>';
	return $output;
}

function pi_available_measures_get_script_measure_nids_for_sort_data_activity_nid($sort_data_activity_nid) {
	$nids = array();

	$query = "SELECT DISTINCT nid FROM {pi_available_measures} WHERE activity_nid=%d AND script_measure=1";
	$result = db_query($query, $sort_data_activity_nid);
	while ($row = db_fetch_array($result)) {
		$nids[] = $row['nid'];
	}

	return $nids;
}

