<?php
// $Id: pi_group_noise.module,v 1.0 2009/11/30 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_group_noise" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_group_noise_node_info() {

    return array(
    'pi_group_noise' => array(
    'name' => t('About your noise data'), // Required.
    'module' => 'pi_group_noise',  // Required.
    'description' => t('About your noise data'), // Required.
    'has_title' => TRUE,
    'title_label' => t('Analysing your group noise data'),
    'has_body' => FALSE,
    'body_label' => t('Analysing your group noise data'),
    'locked' => TRUE)
    );

}


/**
 * Implementation of hook_perm().
 */

function pi_group_noise_perm() {
    return array('create pi_group_noise content', 'edit pi_group_noise');
}

/**
 * Implementation of hook_access().
 */
function pi_group_noise_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    }
}

/**
 * Implementation of hook_form().
 */

function pi_group_noise_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_group_noise_node_info().
    $type = node_get_types('type', $node);
  	global $user;
  
  	$node_details = get_inquiry_details_from_current_path();
  	if (is_numeric($node_details->activity_id)) {
  		$current_activity = load_activity($node_details->activity_id);
  	}
  	
  	if ($current_activity->name) {
  		drupal_set_title(t($current_activity->name));
  	}

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );
    $which_options = array('Tree 1' => 'Tree 1', 'Tree 2' => 'Tree 2', 'Tree 3' => 'Tree 3', 'Tree 4' => 'Tree 4', 'Tree 5' => 'Tree 5', 'Tree 6' => 'Tree 6');
    $form['which'] = array(
        '#type' => 'select',
        '#title' => t('Which location did you choose?'),
        '#required' => TRUE,
        '#default_value' => $node->which,
        '#options' => $which_options,
        '#weight' => -4
    );
    $form['average'] = array(
        '#type' => 'textarea',
        '#title' => t('What was the average background noise?'),
        '#required' => FALSE,
        '#default_value' => $node->coverage,
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -3
    );
    $form['highest'] = array(
        '#type' => 'textarea',
        '#title' => t('What was the highest level of noise?'),
        '#required' => FALSE,
        '#default_value' => $node->highest,
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -2
    );
        $form['lowest'] = array(
        '#type' => 'textarea',
        '#title' => t('What was the lowest level of noise?'),
        '#required' => FALSE,
        '#default_value' => $node->lowest,
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -1
    );
	$form['time'] = array(
        '#type' => 'textarea',
        '#title' => t('Can you identify the time of the day of the highest noise?'),
        '#required' => FALSE,
        '#default_value' => $node->time,
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => 0
    );
    	$form['source'] = array(
        '#type' => 'textarea',
        '#title' => t('Can you tell what might be the source of that peak noise?'),
        '#required' => FALSE,
        '#default_value' => $node->source,
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => 1
    );

    $prefix = "";

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>Analysing your group's noise data</p>";
    }
*/
    
    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_group_noise_insert($node) {
    db_query("INSERT INTO {pi_group_noise} (nid, vid, which, average, highest, lowest, time, source ) VALUES ('%d', '%d', '%s', '%s', '%s', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->which, $node->average, $node->highest, $node->lowest, $node->time, $node->source);
} 

/* Implementation of hook_update().
 */

function pi_group_noise_update($node) {
    if ($node->revision) {
        pi_group_noise_insert($node);
    }

    else {
        db_query("UPDATE {pi_group_noise} SET which = '%s', average = '%s', highest = '%s', lowest = '%s', time = '%s', source = '%s' WHERE vid = %d", $node->which, $node->average, $node->highest, $node->lowest, $node->time, $node->source, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_group_noise_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_group_noise} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_group_noise_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_group_noise} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_group_noise_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_group_noise'] = array(
            '#value' => theme('pi_group_noise', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_group_noise_theme() {
    return array(
    'pi_group_noise' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_group_noise($node) {

    $output = '<p><strong>Which location did you choose?</strong> ' . check_plain($node->which). '</p>';
    $output .= '<p><strong>What was the average background noise?</strong> ' . check_plain($node->average). '</p>';
    $output .= '<p><strong>What was the highest level of noise?</strong> ' . check_plain($node->highest). '</p>';
    $output .= '<p><strong>What was the lowest level of noise?</strong> ' . check_plain($node->lowest). '</p>';
    $output .= '<p><strong>Can you identify the time of the day of the highest noise?</strong> ' . check_plain($node->time). '</p>';
    $output .= '<p><strong>Can you tell what might be the source of that peak noise?</strong> ' . check_plain($node->source). '</p>';

    return $output;
}

