<?php

// $Id: pi_hypothesis_conclusion.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module to create "pi_hypothesis_conclusion" node type
 */

/**
 * Implementation of hook_node_info().
 */
function pi_hypothesis_conclusion_node_info() {
  return array(
      'pi_hypothesis_conclusion' => array(
          'name' => t('Inquiry hypothesis conclusion'), // Required.
          'module' => 'pi_hypothesis_conclusion', // Required.
          'description' => t('What is your conclusion?'), // Required.
          'has_title' => TRUE,
          'title_label' => t('Inquiry conclusion'),
          'has_body' => TRUE,
          'body_label' => t('My conclusion is'),
          'locked' => TRUE
      )
  );
}

/**
 * Implementation of hook_access().
 */
function pi_hypothesis_conclusion_access($op, $node, $account) {
  return FALSE;
}

function pi_hypothesis_conclusion_edit_content_label() {
  return t('Edit');
}

/**
 * Implementation of hook_form() for pi_hypothesis_conclusion
 */
function pi_hypothesis_conclusion_form(&$node) {
  global $user;
  $current_path = pi_info()->getCurrentPath();

  $type = node_get_types('type', $node);
  $node_title = $type->name;

  $form['title'] = array(
      '#type' => 'hidden',
      '#title' => check_plain($type->title_label),
      '#required' => FALSE,
      '#default_value' => $node_title,
      '#weight' => -5
  );

  $form['conclusion'] = array(
      '#type' => 'textarea',
      '#title' => $type->body_label,
      '#required' => FALSE,
      '#default_value' => $node->conclusion,
      '#description' => t('Type your answer into the above box and click on the Save button when you are finished'),
      '#resizable' => FALSE,
      '#rows' => 8,
      '#cols' => 40,
      '#weight' => -2
  );

  return $form;
}

/**
 * Implementation of hook_insert().
 */
function pi_hypothesis_conclusion_insert($node) {
  db_query("INSERT INTO {pi_hypothesis_conclusion} (nid, vid, conclusion) VALUES ('%d', '%d', '%s')", $node->nid, $node->vid, $node->conclusion);
}

/**
 * Implementation of hook_update().
 */
function pi_hypothesis_conclusion_update($node) {
  if ($node->revision) {
    pi_hypothesis_conclusion_insert($node);
  } else {
    db_query("UPDATE {pi_hypothesis_conclusion} SET conclusion = '%s' WHERE vid = %d", $node->conclusion, $node->vid);
  }
}

/**
 * Implementation of hook_delete().
 */
function pi_hypothesis_conclusion_delete(&$node) {
  // Delete the related information we were saving for this node.
  db_query('DELETE FROM {pi_hypothesis_conclusion} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */
function pi_hypothesis_conclusion_load($node) {
  return db_fetch_object(db_query('SELECT * FROM {pi_hypothesis_conclusion} WHERE vid = %d', $node->vid));
}

function pi_hypothesis_conclusion_display_content_in_activity($node, $options) {
  global $user;

  $hypothesis_nids = pi_hypothesis_get_hypothesis_nids_for_use_in_activity($options['activity_node']->nid, $user->uid);

  $rows = array();

  if ($options['editable']) {

    if ($hypothesis_nids) {
      $hypotheses = array_filter(array_map(function($nid) {
                $node = node_load($nid);
                return trim(check_plain($node->hypothesis));
              }, $hypothesis_nids));

      if (count($hypotheses) === 1) {
        $h_content = $hypotheses[0];
      } else if (count($hypotheses) > 0) {
        $h_content = theme('item_list', $hypotheses);
      } else {
        $h_content = FALSE;
      }

      if ($h_content) {
        $rows[] = array(t('Hypothesis:'), $h_content);
      }
    }
  }

  if ($options['edit']) {
    $c_content = node_page_edit($node);
  } else {
    $c_content = array(
        'content' => $node ? check_plain($node->conclusion) : t('Create your conclusion.'),
        'empty' => ! ((bool) $node),
        'edit_link' => TRUE,
        );
  }

  $rows[] = array(t('Conclusion:'), $c_content);

  return array(
      'mode' => 'twocolumns',
      'rows' => $rows,
  );
}

function pi_hypothesis_conclusion_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  return $node;
}

/**
 * Theme function to display the pi_hypothesis_conclusion view page (uses drupal theme_hook())
 * @param object(node) $node Drupal node of type pi_hypothesis_conlcusion
 * @param object(pi_activity) $current_activity default NULL, pi_activity object that's linked to this node
 * @return string HTML for the page content added for hypothesis conclusion data
 */
function theme_pi_hypothesis_conclusion($node, $teaser) {
  $output = '<strong>' . t('Conclusion:') . '</strong> ' . nl2br($node->conclusion);
  return $output;
}

function pi_hypothesis_conclusion_create_shared_view($node) {
  return theme('pi_hypothesis_conclusion', $node, FALSE);
}

function pi_hypothesis_conclusion_links_edit_content_click() {
  return TRUE;
}
