<?php
// $Id$: pi_selected_locations.module ou_mbg Exp $

/**
 * @file
 * Provides a "selected_measures" node type.
 */

/**
 * Implementation of hook_node_info().
 */
function pi_selected_measures_node_info() {
  // We return an array since a module can define multiple node types.
  // We're only defining one node type, type 'pi_selected_measures'.
  return array(
    'pi_selected_measures' => array(
      'name' => t('Selected measures'), // Required.
      'module' => 'pi_selected_measures',  // Required.
      'description' => t('Select one or more measures for carrying out your inquiry'), // Required.
      'has_title' => TRUE,
      'title_label' => t('Pick measurements'),
      'has_body' => TRUE,
      'body_label' => t('Measures'),
      'locked' => TRUE
    )
  );
}
//Commented out as no longer used in Drupal 6. Previously only the hook_menu line was active MBG 09_08_11
/**
 * Implementation of hook_menu().
 */
//function pi_selected_measures_menu($may_cache) {
//  $items = array();
//
//  // Do not cache this menu item during the development of this module.
//  if (!$may_cache) {
//    $items[] = array(
//      'path' => 'node/add/pi_selected_measures',
//      'title' => t('Selected measures'),
//      'access' => user_access('create selected_measures'),
//    );
//  }
//
//  return $items;
//}

/**
 * Implementation of hook_perm().
 */
function pi_selected_measures_perm() {
  return array();
}

/**
 * Implementation of hook_access().
 */
function pi_selected_measures_access($op, $node) {
  global $user;
  $details = get_inquiry_details_from_current_path();

  if ($op == 'create') {
    return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
  }

  if ($op == 'update' || $op == 'delete') {
    return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
  }
}

/**
 * Implementation of hook_form().
 */
function pi_selected_measures_form(&$node) {
  
  drupal_set_title(t('Pick measurements'));

  $type = node_get_types('type', $node);

  global $user;
  $uid = $user->uid;
  
  $results = db_query("SELECT nid,title FROM node WHERE type = 'pi_available_measures' AND status = '1'");
  $options = array();
  
  while ($result = db_fetch_array($results)) {
    $options[$result['nid']] = $result['title'];
  }

  $form['title'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->title_label),
    '#required' => FALSE,
    '#default_value' => 'Pick measurements',
    '#weight' => -5
  );
  $form['body_filter']['body'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->body_label),
    '#required' => FALSE,
    '#default_value' => NULL,
    '#rows' => 5,
    '#weight' => -1
  );
  $form['selected_measures'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Available measurements'),
    '#required' => TRUE,
    '#multiple' => TRUE,
    '#default_value' => find_default_measures($node->nid),//explode(",", $node->selected_measures),
    '#options' => $options,
    '#weight' => 5
  );
  
  
  
  $prefix = "<p>Pick which measurements you need. Click on the tabs on the right to find out more about these measurements.</p>";
  
  $form['#prefix'] = $prefix;

  return $form;
}

function find_default_measures($nid) {
	$measure_array = array();
	$prev_query = "SELECT measure_nid FROM pi_selected_measures WHERE nid = '" . $nid . "' ORDER BY weight ASC";
	$db_result = db_query($prev_query);
  	while ($prev_result = db_fetch_object($db_result)) {
  		$prev_result = $prev_result->measure_nid;
  		$measure_array[] = $prev_result;
  	}
  	return $measure_array;
}

function find_default_measure_rows($nid) {
	$measure_array = array();
	$prev_query = "SELECT * FROM pi_selected_measures WHERE nid = '" . $nid . "' ORDER BY weight ASC";
	$db_result = db_query($prev_query);
  	while ($prev_result = db_fetch_object($db_result)) {
  		$measure_array[] = $prev_result;
  	}
  	return $measure_array;
}

/**
 * Implementation of hook_validate().
 */
function pi_selected_measures_validate($node) {
  // Enforce a minimum word length of 3.
  if (isset($node->selected_measures) && count($node->selected_measures) < 1) {
    $type = node_get_types('type', $node);
    form_set_error('selected_measures', t('Your @type is too short. You need at least one measure.', array('@type' => $type->name)));
  }
}

/**
 * Implementation of hook_insert().
 */
function pi_selected_measures_insert($node) {
  $new_selected_measures = array();
  foreach ($node->selected_measures as $measure) {
  	if ($measure != 0) {
  		$measure_node = node_load($measure);
  		if ($measure_node->title == "Name of the person being interviewed") {
  			$weight = 0;
  		}
  		else {
  			$weight = 1;
  		}
  		db_query("INSERT INTO pi_selected_measures (nid, vid, measure_nid, weight) VALUES (%d, %d, %d, %d) ", $node->nid, $node->nid, $measure, $weight);
  	};
  };
}

/**
 * Implementation of hook_update().
 */
function pi_selected_measures_update($node) {
  if ($node->revision) {
    pi_selected_measures_insert($node);
  }
  else {
    db_query('DELETE FROM {pi_selected_measures} WHERE nid = %d', $node->nid);
    pi_selected_measures_insert($node);
  }
}

/**
 * Implementation of hook_delete().
 */
function pi_selected_measures_delete(&$node) {
  // Delete the related information we were saving for this node.
  /*db_query('DELETE FROM {pi_selected_measures} WHERE nid = %d', $node->nid);*/
}


/**
 * Implementation of hook_load().
 */
function pi_selected_measures_load($node) {
  $result = new stdClass;
  $result->selected_measures = find_default_measures($node->nid);
  $result->measure_rows = find_default_measure_rows($node->nid);
  return $result;
}

/**
 * Implementation of hook_view().
 */
function pi_selected_measures_view($node, $teaser = FALSE, $page = FALSE) {
  if (!$teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);

    $node->content['pi_selected_measures'] = array(
      '#value' => theme('pi_selected_measures', $node),
      '#weight' => 2
      );
  }

  if ($teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);
  }

  return $node;
}


function theme_pi_selected_measures($node) {
  drupal_set_title(t('Pick measurements'));
  
  $output = "hello";
  
  $selected_measures = find_default_measures($node->nid);
  
  foreach ($selected_measures as $measure_id) {
    $measure_node = node_load($measure_id);
    $output .= '<div class="teaser_list">';
    $output .= '<h3>' . l($measure_node->title, 'node/' . $measure_node->nid) . '</h3>';
    if (isset($measure_node->image_id)) {
      $output .= '<img style="float: left; clear: left; padding: 0 10px 1.8em 0;" src="' . url("image/view/" . $measure_node->image_id . "/thumbnail") . '" />';
    };
    $body = t($measure_node->body);
    if (strlen($body) > 70) {
      $body = substr($body, 0, 70) . '...';
    };
    $output .= $body . '<br />';
    if (isset($measure_node->units_short) AND ($measure_node->units_short != '')) {
      $output .= t('<strong>Units: </strong>' . $measure_node->units_short);
    }
    elseif (isset($measure_node->units) AND ($measure_node->units != '')) {
      $output .= t('<strong>Units: </strong>' . $measure_node->units);
    };
    $output .= '</div>';
  }
  
  return $output;
}
