<?php
// $Id: pi_about_noise.module,v 1.0 2009/11/20 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_about_noise" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_about_noise_node_info() {

    return array(
    'pi_about_noise' => array(
    'name' => t('About noise'), // Required.
    'module' => 'pi_about_noise',  // Required.
    'description' => t('About noise'), // Required.
    'has_title' => TRUE,
    'title_label' => t('About noise'),
    'has_body' => FALSE,
    'body_label' => t('About Noise'),
    'locked' => TRUE)
    );

}


/**
 * Implementation of hook_perm().
 */

function pi_about_noise_perm() {
    return array('create pi_about_noise content', 'edit pi_about_noise');
}

/**
 * Implementation of hook_access().
 */
function pi_about_noise_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    }
}

/**
 * Implementation of hook_form().
 */

function pi_about_noise_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_about_noise_node_info().
    $type = node_get_types('type', $node);
  	global $user;
  
  	$node_details = get_inquiry_details_from_current_path();
  	if (is_numeric($node_details->activity_id)) {
  		$current_activity = load_activity($node_details->activity_id);
  	}
  	
  	if ($current_activity->name) {
  		drupal_set_title(t($current_activity->name));
  	}

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );

    $form['which'] = array(
        '#type' => 'textarea',
        '#title' => t('Which route was the noisiest?'),
        '#required' => FALSE,
        '#default_value' => $node->which,
        '#description' => t('Type in which route you thought was the noisiest'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -4
    );
    $form['whatparts'] = array(
        '#type' => 'textarea',
        '#title' => t('What parts were the noisiest?'),
        '#required' => FALSE,
        '#default_value' => $node->whatparts,
        '#description' => t('Type in what parts of the routes were the noisiest'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -3
    );
    $form['cause'] = array(
        '#type' => 'textarea',
        '#title' => t('What caused the noises?'),
        '#required' => FALSE,
        '#default_value' => $node->cause,
        '#description' => t('Type in what you think caused the noises'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -2
    );

    $prefix = "";

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>About noise.</p>";
    }
*/
    
    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_about_noise_insert($node) {
    db_query("INSERT INTO {pi_about_noise} (nid, vid, which, whatparts, cause) VALUES ('%d', '%d', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->which, $node->whatparts, $node->cause);
} 

/* Implementation of hook_update().
 */

function pi_about_noise_update($node) {
    if ($node->revision) {
        pi_about_noise_insert($node);
    }

    else {
        db_query("UPDATE {pi_about_noise} SET which = '%s', whatparts = '%s', noise = '%s'  WHERE vid = %d", $node->which, $node->whatparts, $node->cause, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_about_noise_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_about_noise} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_about_noise_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_about_noise} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_about_noise_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_about_noise'] = array(
            '#value' => theme('pi_about_noise', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_about_noise_theme() {
    return array(
    'pi_about_noise' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_about_noise($node) {

    $output = '<p><strong>Which route was the noisiest?</strong> ' . check_plain($node->which). '</p>';
    $output .= '<p><strong>What parts were the noisiest?</strong> ' . check_plain($node->whatparts). '</p>';
    $output .= '<p><strong>How caused the noisiest?</strong> ' . check_plain($node->cause). '</p>';

    return $output;
}

