<?php
// $Id: pi_available_content_types.info,  2010/05/21  PM $

/**
 * Implementation of hook_perm().
 */
function pi_available_content_types_perm() {
  return array();
}

function pi_available_content_types_access($op, $node, $account) {
  return TRUE;
}

function pi_available_content_types_menu() {
  
  $items = array();

  $items['admin/nquire/pi-available-content-types'] = array(
    'title' => 'Available content types',
    'description' => 'Manage available content types that can be used for measures',
    'page callback' => 'pi_available_content_types_admin',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/nquire/pi-available-content-types/list'] = array(
    'title' => 'List',
    'description' => 'List all available content types',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  ); 

  $items['admin/nquire/pi-available-content-types/add'] = array(
    'title' => 'Add',
    'description' => 'Add to the list of available content types',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pi_available_content_types_edit'),
    //'page callback' => pi_available_content_types_edit,
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/nquire/pi-available-content-types/delete/%'] = array(
    'title' => 'Remove available content type',
    'description' => 'Remove from the list of available content types',
    'page callback' => 'pi_available_content_types_delete',
    'page arguments' => array(4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}


function pi_available_content_types_admin() {
  $query = "SELECT DISTINCT type FROM {pi_available_content_types} ORDER BY {pi_available_content_types}.type ASC";
  $result = db_query($query);
  
  $rows = array();
  
  while($content_type = db_fetch_object($result)) {
    $row = array($content_type->type, l( t('remove'), 'admin/nquire/pi-available-content-types/delete/'.$content_type->type));
    $rows[] = array('data' => $row);
  }
  $output .= "<p>" . t('Content types available for use as measures') ."</p>";
  $output .= theme('table', $header, $rows);
  return $output;
}

function pi_available_content_types_edit($form_state) {
    drupal_set_title(t('Add content type'));
    $output  = pi_available_content_types_form($form_state);
    return $output;  
}

function pi_available_content_types_form(&$form_state, $edit = array()) {
  $form['#prefix'] = "Select a content type to add to the list of available content types";

  $content_types = array();
  $query = "SELECT DISTINCT {node_type}.type FROM {node_type} LEFT JOIN {pi_available_content_types} ON {pi_available_content_types}.type = {node_type}.type WHERE {pi_available_content_types}.type IS NULL ";
  //$query = "SELECT DISTINCT node_type.type FROM node_type, pi_available_content_types WHERE NOT EXISTS (SELECT * FROM pi_available_content_types WHERE node_type.type = pi_available_content_types.type) ORDER BY node_type.type ASC";
  $result = db_query($query);
  while($row = db_fetch_object($result)) {
    $content_types[$row->type] .= $row->type;
  }
  
  $form['choice'] = array(
    '#type' => 'select',
    '#options' => $content_types,
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'), '#submit' => array('pi_available_content_types_insert'));
  $form['cancel'] = array('#value' => l(t('Cancel'), 'admin/nquire/pi-available-content-types'));
  
  return $form;
}

function pi_available_content_types_submit($form, &$form_state) {
  //path_redirect_save($form_state['values']);
  drupal_set_message(t('Redirect has been saved.'));
}

function pi_available_content_types_insert($node) {
  $content_type = $node["choice"]["#value"];
  if($content_type) {
    db_query("INSERT INTO {pi_available_content_types} (type) VALUES ('%s')", $content_type);
  }
  drupal_goto('admin/nquire/pi-available-content-types');
}

function pi_available_content_types_delete($arg) {
  drupal_set_title(t($arg));
  db_query("DELETE FROM {pi_available_content_types} WHERE type = '%s' ", $arg);
  drupal_goto('admin/nquire/pi-available-content-types');
}
