<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function google_maps_measure_designer_install() {
  inquiry_available_features_register('measure', '_googlemap', 'google_maps_measure_designer');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function google_maps_measure_designer_uninstall() {
  inquiry_available_features_forget('measure', '_googlemap');
}

