<?php

/**
 * Implementation of nQuire Creator hook 'form' for 'hypothesis' activity.
 * 
 * @param type $activity
 * @param type $design
 * @param type $form
 */
function inquiry_basic_activities_nquire_creator_activity_hypothesis_form($activity, $design, &$form) {
  $data = json_decode($activity->data);

  $form['data']['hypothesis'] = array(
      '#type' => 'textarea',
      '#title' => t('Default hypothesis'),
      '#description' => t('You can propose a default hypothesis, or leave it blank if users must write the hypothesis on their own.'),
      '#default_value' => '',
      '#required' => FALSE,
  );
  $form['data']['editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Is the default Hypothesis editable?'),
      '#description' => t('Select this option if the hypothesis can be modified by the inquiry participants.'),
      '#default_value' => TRUE,
  );
}

function inquiry_basic_activities_nquire_creator_activity_keyquestions_form($activity, $design, &$form) {
  $data = json_decode($activity->data);

  nquire_list_widget_create_form_item($form['data'], 'keyquestions', '', t('Default key questions:'), t('You can add some default key questions, or leave this blank for the users to create their own.')
          . '<br/>' . t('Leave the question slots empty if you do not want to add questions.'));

  $form['data']['editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Are the default Key questios editable?'),
      '#description' => t('Select this option if the users are allows to edit, create and delete their key questions.'),
      '#default_value' => TRUE,
  );
}

