<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_activities_install() {
  inquiry_available_activities_register('notes', 'inquiry_basic_activities');
  inquiry_available_activities_register('hypothesis', 'inquiry_basic_activities');
  inquiry_available_activities_register('keyquestions', 'inquiry_basic_activities');
  inquiry_available_activities_register('collectdata', 'inquiry_basic_activities');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_activities_uninstall() {
  inquiry_available_activities_forget('notes');
  inquiry_available_activities_forget('hypothesis');
  inquiry_available_activities_forget('keyquestions');
  inquiry_available_activities_forget('collectdata');
}

