<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_activities_install() {
  inquiry_available_features_register('activity', 'notes', 'inquiry_basic_activities');
  inquiry_available_features_register('activity', 'hypothesis', 'inquiry_basic_activities');
  inquiry_available_features_register('activity', 'keyquestions', 'inquiry_basic_activities');
  inquiry_available_features_register('activity', 'collectdata', 'inquiry_basic_activities');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_activities_uninstall() {
  inquiry_available_features_forget('activity', 'notes');
  inquiry_available_features_forget('activity', 'hypothesis');
  inquiry_available_features_forget('activity', 'keyquestions');
  inquiry_available_features_forget('activity', 'collectdata');
}

