<?php

function inquiry_basic_activities_menu() {
  $items['creator/toolform'] = array(
      'page callback' => 'inquiry_basic_activities_update_toolform',
      'access arguments' => array('access inquiry_creator content'),
      'type' => MENU_CALLBACK,
      'file' => 'inquiry_basic_activities.tools.inc',
  );
  return $items;
}

/**
 * Implementation of nQuire Creator hook 'form' for 'hypothesis' activity.
 * 
 * @param type $activity
 * @param type $design
 * @param type $form
 */
function inquiry_basic_activities_nquire_creator_activity_hypothesis_form($activity, $design, &$form, &$form_state) {
  $data = $data = nquire_commons_decode_data($activity->data);

  $form['data']['hypothesis'] = array(
      '#type' => 'textarea',
      '#title' => t('Default hypothesis'),
      '#description' => t('You can propose a default hypothesis, or leave it blank if users must write the hypothesis on their own.'),
      '#default_value' => nquire_commons_form_data_default_value($data, 'hypothesis', $form_state, 'hipothesis', ''),
      '#required' => FALSE,
  );
  $form['data']['hypothesis_editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Is the default Hypothesis editable?'),
      '#description' => t('Select this option if the hypothesis can be modified by the inquiry participants.'),
      '#default_value' => nquire_commons_form_data_default_value($data, 'hypothesis_editable', $form_state, 'hypothesis_editable', TRUE),
  );
}

/**
 * Implementation of nQuire Creator hook 'form_process' for 'hypothesis' activity.
 * 
 * @param type $activity
 * @param type $design
 * @param type $form
 */
function inquiry_basic_activities_nquire_creator_activity_hypothesis_form_process(&$activity, $design, $form_values) {
  $data = array();
  $data['hypothesis'] = $form_values['hypothesis'];
  $data['hypothesis_editable'] = $form_values['hypothesis_editable'];

  $new_data = json_encode($data);
  if ($activity->data !== $new_data) {
    $activity->data = $new_data;
    return TRUE;
  } else {
    return FALSE;
  }
}

function inquiry_basic_activities_nquire_creator_activity_keyquestions_form($activity, $design, &$form, &$form_state) {
  $data = nquire_commons_decode_data($activity->data);

  $value = nquire_commons_form_data_default_value($data, 'keyquestions', $form_state, 'keyquestions', '[]');
  $title = t('Default key questions:');
  $addItemLabel = t('Add key question');
  $description = t('You can add some default key questions, or leave this blank for the users to create their own.')
          . '<br/>' . t('Leave the question slots empty if you do not want to add questions.');

  nquire_list_widget_create_form_item($form['data'], 'keyquestions', $value, $title, $addItemLabel, $description);

  $form['data']['keyquestions_editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Are the default Key questios editable?'),
      '#description' => t('Select this option if the users are allows to edit, create and delete their key questions.'),
      '#default_value' => nquire_commons_form_data_default_value($data, 'keyquestions_editable', $form_state, 'keyquestions_editable', TRUE),
  );
}

function inquiry_basic_activities_nquire_creator_activity_keyquestions_form_process(&$activity, $design, $form_values) {
  $data = array();
  $data['keyquestions'] = $form_values['keyquestions'];
  $data['keyquestions_editable'] = $form_values['keyquestions_editable'];

  $new_data = json_encode($data);
  if ($activity->data !== $new_data) {
    $activity->data = $new_data;
    return TRUE;
  } else {
    return FALSE;
  }
}

function inquiry_basic_activities_nquire_creator_activity_collectdata_form($activity, $design, &$form, &$form_state) {
  $data = nquire_commons_decode_data($activity->data);

  $title = t('Scientific instrument');
  $description = t('Select a scientific instrument that the participants will use to collect data. ')
          . '<br/>' . t('Alternatively, select \'No instrument\' if data will be manually entered by the users.');

  module_load_include('inc', 'inquiry_basic_activities', 'inquiry_basic_activities.tools');
  _inquiry_basic_activities_tool_form($form, $form_state, $data, $title, $description, TRUE, "creator/{$design->nid}/activity/{$activity->nid}");
}

function inquiry_basic_activities_nquire_creator_activity_collectdata_form_process(&$activity, $design, $form_values) {
  module_load_include('inc', 'inquiry_basic_activities', 'inquiry_basic_activities.tools');
  return _inquiry_basic_activities_tool_form_process($activity, $design, $form_values);
}

function inquiry_basic_activities_nquire_creator_activity_collectdata_delete(&$activity) {
  $data = nquire_commons_decode_data($activity->data);
  if (isset($data['measures'])) {
    foreach($data['measures'] as $measure_nid) {
      inquiry_creator_delete_measure_node($measure_nid);
    } 
  }
}

function inquiry_basic_activities_nquire_creator_activity_exploretool_form($activity, $design, &$form, &$form_state) {
  $data = nquire_commons_decode_data($activity->data);

  $title = t('Scientific instrument');
  $description = t('Select a scientific instrument that the participants will explore. ');

  module_load_include('inc', 'inquiry_basic_activities', 'inquiry_basic_activities.tools');
  _inquiry_basic_activities_tool_form($form, $form_state, $data, $title, $description, FALSE, "creator/{$design->nid}/activity/{$activity->nid}");
}

function inquiry_basic_activities_nquire_creator_activity_exploretool_form_process(&$activity, $design, $form_values) {
  module_load_include('inc', 'inquiry_basic_activities', 'inquiry_basic_activities.tools');
  return _inquiry_basic_activities_tool_form_process($activity, $design, $form_values);
}
