<?php
// $Id: questions_import.module,v 1.1.2.2 2009/12/27 14:04:17 sivaji Exp $

/**
 * @file
 * Questions Import
 *
 * This module allows you to import questions to quiz node in CSV, QTI XML, Moodle Aiken format.
 */

/**
 * Implementation of hook_help().
 */

function questions_import_help($path, $arg) {
  if ($path == 'admin/help#questions_import') {
    return '<p>' . t('This module allows you to import questions to quiz node in CSV, QTI XML, Moodle Aiken format.') . '</p>';
  }
}

/**
 * Implementation of hook_perm()
 * Valid permissions for this module
 * @return array An array of valid permissions.
 */

function questions_import_perm() {
  return array('import questions');
}

/**
 * Implementation of hook_menu
 *
 */

function questions_import_menu() {
  $items = array();
  $items['admin/quiz/questions_import'] = array(
    'title' => t('Import Quiz Questions'),
    'description' => t('Import Questions is an addon for quiz module. It allows to create a bulk of quiz questions from files. Allowed file formats are CSV, Moodle Aiken and QTI format.'),
    'file' => 'questions_import.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('questions_import_form'),
    'access arguments' => array('import_questions'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
