<?php

/**
 * Implementation of hook_init().
 */
function pi_ag_inquiry_select_init() {
}

/**
 * @file
 * Implements block for Activity Guide Inquiry selection.
 */
 
 /**  and n.uid = %d' $uid,
 * Implementation of hook_block().
 */
function pi_ag_inquiry_select_block($op = 'list', $delta = 0, $edit = array())
{
	switch ($op) {
  
    case 'list':
		$blocks[0]['info'] = t('PI Inquiry Selection');
		return $blocks;

	case 'view':
		global $user;
		$image_path = "images/";
		$node_details = get_inquiry_details_from_current_path();
		//get default inquiry_id if not set
		if($node_details->inquiry_id)
		{
			$inquiry = load_inquiry($node_details->inquiry_id);
		}
		else
		{
			$db_result = get_inquiries_of_user ($user->uid);
			$inquiry = db_fetch_object($db_result);
		}

		$ag_content = pi_ag_inquiry_select_content($user, $inquiry, $node_details);
		$block['content'] = "$ag_content";
		return $block;
	};
}

function pi_ag_inquiry_select_content($user, $inquiry, $node_details)
{
    $current_stage = get_current_stage_of_inquiry_and_user($inquiry->inquiry_id, $user->uid);

	/// Generate list of enquiries currently available for user
	$db_result = get_inquiries_of_user($user->uid);
	$user_inquiries = array();

	// sort inquiries by id
	while($each_inquiry=db_fetch_object($db_result)) 
	{
		$user_inqueries[$each_inquiry->inquiry_id] = $each_inquiry;
	}
	if($user_inqueries==null) 
	{
		$user_inqueries=array();
	}
	asort($user_inqueries);

	$content = "<div id='pi_ag_inquiries_list'>";
	
	$content .= "<div id='pi_ag_inquiries_list_title' class='pi_ag_inquiry'>";
	$content .= l("Inquiry Guide", '<front>');
	$content .= "</div>";
	
	foreach($user_inqueries as $each_inquiry) 
	{
		$each_enquiry_stage = get_current_stage_of_inquiry_and_user($each_inquiry->inquiry_id, $user->uid);
		if(($each_enquiry_stage!=NULL) || ($each_inquiry->inquiry_id==$inquiry->inquiry_id))
		{
			if($each_inquiry->inquiry_id==$inquiry->inquiry_id)
			{
				$div_attributes = "id='pi_ag_inquiry-current'";
			}
			else
			{
				$div_attributes='';
			}
			$content.="<div class='pi_ag_inquiry' $div_attributes >" 
				. l($each_inquiry->name, build_home_link($each_inquiry->inquiry_id, $current_stage->stage_id, '', ''))
				. "</div>\n";
		}
	}
	$content .= "</div>\n";

	return $content;
}
