<?php

require_once( 'lib/pChart/pData.class.php');
require_once( 'lib/pChart/pDraw.class.php');
require_once( 'lib/pChart/pScatter.class.php');
require_once( 'lib/pChart/pImage.class.php');

/*
  require_once( 'lib/pChart/pData.class.1.26.php');
  require_once( 'lib/pChart/pChart.class.1.26.php');
 */

function pi_chart_menu() {
  $items['activity/%node/chart/%node/chart.png'] = array(
      'page callback' => 'pi_chart_create_png',
      'page arguments' => array(1, 3),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  $items['pi_chart/tempchart.png'] = array(
      'page callback' => 'pi_chart_show_chart_as_temppnlg',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  $items['activity/%/tempchart.png'] = array(
      'page callback' => 'pi_chart_show_chart_as_temppng',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );


  return $items;
}

function pi_chart_show_chart_as_temppng() {
  $title = $_REQUEST['title'];
  $type = $_REQUEST['type'];
  $abscissa_nid = $_REQUEST['abscissa'];
  $ordinate_str = $_REQUEST['ordinate'];
  $color_nid = $_REQUEST['color'];
  $question = $_REQUEST['question'];

  global $user;

  if (strlen($type) > 0 && strlen($abscissa_nid) > 0 && strlen($ordinate_str) > 0) {
    pi_chart_create_png($title, $type, $abscissa_nid, $ordinate_str, $color_nid, $question, $user->uid);
  }
  return;
}

function pi_chart_create_png($activity_node, $chart_node) {
  global $user;

  $ordinate_measures = explode(',', $chart_node->ordinate);
  $measures = array_merge(array($chart_node->abscissa), $ordinate_measures);
  $key_numeric = pi_data_tools_measure_plugin_submeasure_is_numeric($chart_node->abscissa);

  $headers = array();
  foreach ($measures as $submeasure_key) {
    $headers[] = pi_data_tools_measure_plugin_submeasure_get_title_for_chart($submeasure_key);
  }

  $data_nids = pi_sort_data_get_all_data_for_use_in_activity_nid($activity_node->nid, $chart_node->uid, $chart_node->data_activity_nid);

  $data = array_map(function($nid) {
            return node_load($nid);
          }, $data_nids);

  $rows = array();
  foreach ($data_nids as $nid) {
    $data = node_load($nid);
    $row = array();
    foreach ($measures as $submeasure_key) {
      $row[] = pi_data_tools_measure_plugin_submeasure_get_value_for_chart_from_data($submeasure_key, $data);
    }
    $rows[] = $row;
  }

  if ($chart_node->chart_type == 'line-bar') {
    if ($key_numeric) {
      $type = 'scatter';
    } else {
      $grouped_rows = array();
      foreach ($rows as $row) {
        if (strlen($row[0]) > 0) {
          $grouped_rows[$row[0]][] = $row;
        }
      }

      $max_data_count_per_key_field = 0;

      foreach ($grouped_rows as $row_group) {
        if (count($row_group) > $max_data_count_per_key_field) {
          $max_data_count_per_key_field = count($row_group);
        }
      }

      if ($max_data_count_per_key_field > 1) {
        $type = 'plot';
      } else {
        $type = 'bar';
      }
    }

    switch ($type) {
      case 'bar':
        _pi_chart_draw_bar_chart($chart_node->title, $headers, $grouped_rows);
        break;
      case 'plot':
        _pi_chart_draw_plot_chart($chart_node->title, $headers, $grouped_rows);
        break;
      case 'scatter':
        _pi_chart_draw_scatter_chart($chart_node->title, $headers, $rows);
      default:
        break;
    }
  } else if ($chart_node->chart_type === 'histogram') {
    $data_index = array(array(), array());
    $data_values = array(array(), array());

    $numeric_data_limits = array(FALSE, FALSE);
    $ngaps = 5;

    for ($i = 0; $i < 2; $i++) {
      if (pi_data_tools_measure_plugin_submeasure_is_numeric($measures[$i])) {
        $min = INF;
        $max = 0.0;
        foreach ($rows as $row) {
          if (strlen($row[$i]) > 0) {
            $min = min($min, $row[$i]);
            $max = max($max, $row[$i]);
          }
        }

        $max_abs_value = max(abs($max), abs($min));
        if ($max_abs_value > 0) {
          $log = log10($max_abs_value);
          $f10 = pow(10, ceil($log) - 2);
          $min = floor($min / $f10) * $f10;
          $max = ceil($max / $f10) * $f10;
        }

        $gap = $max > $min ? ($max - $min) / $ngaps : 5;
        $limits = array();
        $ft = function($f) {
                  $t = "$f";
                  if (strlen($t) > 1 && $t[0] == '0') {
                    $t = substr($t, 1);
                  }
                  return $t;
                };

        for ($j = 0; $j < $ngaps; $j++) {
          $l0 = $min + $j * $gap;
          $l1 = $l0 + $gap;

          $limits[$j] = $l1;
          $data_values[$i][$j] = $ft($l0) . ' - ' . $ft($l1);
        }
        $numeric_data_limits[$i] = $limits;
      } else {
        foreach ($rows as $row) {
          if (strlen($row[$i]) > 0) {
            $v = $row[$i];
            if (!isset($data_index[$i][$v])) {
              $j = count($data_index[$i]);
              $data_index[$i][$v] = $j;
              $data_values[$i][$j] = $v;
            }
          }
        }
      }
    }
    $cross = array_fill(0, max(1, count($data_index[0])), array_fill(0, max(1, count($data_index[1])), 0));
    foreach ($rows as $row) {
      $indexes = array(-1, -1);
      for ($i = 0; $i < 2; $i++) {
        if (strlen($row[$i]) > 0) {
          if ($numeric_data_limits[$i]) {
            $v = $row[$i];
            for ($j = 0; $j < $ngaps - 1; $j++) {
              if ($numeric_data_limits[$i][$j] >= $v) {
                break;
              }
            }
            $indexes[$i] = $j;
          } else {
            $indexes[$i] = $data_index[$i][$row[$i]];
          }
        }
      }

      if ($indexes[0] >= 0 && $indexes[1] >= 0) {
        $cross[$indexes[0]][$indexes[1]]++;
      }
    }


    _pi_chart_draw_histogram($chart_node->title, $headers, $numeric_data_limits, $cross, $data_values);
  }

  return;
}

function _pi_chart_get_numeric_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_numeric_value";
    return $function_name($value);
  } else {
    return strlen($value) > 0 ? floatval($value) : VOID;
  }
}

function _pi_chart_get_color_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_color_value";
    return $function_name($value);
  } else {
    return array("R" => 255, "G" => 255, "B" => 255, "Alpha" => 127);
  }
}

function _pi_chart_get_text_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_text_value";
    return $function_name($value);
  } else {
    return check_plain($value);
  }
}

function _pi_chart_get_html_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_html_value";
    return $function_name($value);
  } else {
    return _pi_chart_get_text_value($value, $type);
  }
}

function pi_chart_get_text_value($value, $type) {
  return _pi_chart_get_text_value($value, $type);
}

function pi_chart_get_html_value($value, $type) {
  return _pi_chart_get_html_value($value, $type);
}

function _pi_chart_prepare_histogram_variable_name($name, $isNumeric) {
  $a = strpos($name, '(');
  if ($a !== FALSE) {
    $b = strpos($name, ')', $a);
    if ($b !== FALSE) {
      $name = trim(substr($name, 0, $a) . substr($name, $b + 1));
    }
  }

  if ($isNumeric) {
    $name .= t(' range');
  }

  return $name;
}

function _pi_chart_draw_histogram($title, $headers, $numeric, $cross, $data_values) {
  /* Create and populate the pData object */

  if ($numeric[0] && !$numeric[1]) {
    $name1 = $headers[0];
    $numeric1 = TRUE;
    $name0 = $headers[1];
  } else {
    $name1 = $headers[1];
    $numeric1 = $numeric[1];
    $name0 = $headers[0];
  }
  $headers[1] = t('No. of ') . $name0 . t("\nper ") . _pi_chart_prepare_histogram_variable_name($name1, $numeric1);

  $MyData = new pData();
  $max = 1;

  /* Add series. There must be only one row group for each key, so we use only $row_group[0]. */
  for ($i = 0; $i < count($data_values[1]); $i++) {
    $series = array();
    for ($j = 0; $j < count($data_values[0]); $j++) {
      $series[] = $cross[$j][$i];
      $max = max($max, $cross[$j][$i]);
    }
    $MyData->addPoints($series, $data_values[1][$i]);
    $MyData->setAxisName(0, $headers[1]);
    if ($colors) {
      $MyData->setPalette($data_values[1][$i], $colors[$i]);
    } else {
      $MyData->setPalette($data_values[1][$i], array("R" => 0, "G" => 200, "B" => 0, "Alpha" => 100));
    }
  }

  $abscissa_series = array();
  for ($j = 0; $j < count($data_values[0]); $j++) {
    $abscissa_series[] = $data_values[0][$j];
  }

  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);

  $myPicture = new pImage(900, 350, $MyData);

  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 899, 349, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 850, 310);
  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => FALSE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_MANUAL,
      "ManualScale" => array(0 => array("Min" => 0, "Max" => $max + 1)),
      "MinDivHeight" => 105.0 / ($max + 1),
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(450, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));

  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  /* Draw the chart */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_INSIDE,
      "DisplaySeriesName" => TRUE,
      "DisplayOrientation" => ORIENTATION_VERTICAL,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
          //"InnerSurrounding" => 100,
  );

  $settings["Gradient"] = TRUE;
  $settings["GradientMode"] = GRADIENT_SIMPLE;

  $myPicture->drawBarChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

function _pi_chart_draw_bar_chart($title, $headers, $grouped_rows) {
  /* Create and populate the pData object */
  $MyData = new pData();

  /* Add series. There must be only one row group for each key, so we use only $row_group[0]. */
  for ($field = 1; $field < count($headers); $field++) {
    $series = array();
    foreach ($grouped_rows as $row_group) {
      if (count($row_group) > 0) {
        $value = $row_group[0][$field];
        $series[] = $value;
      }
    }
    $MyData->addPoints($series, $headers[$field]);
    $MyData->setAxisName(0, $headers[$field]);
  }

  $abscissa_series = array();
  foreach ($grouped_rows as $key => $row_group) {
    if (count($row_group) > 0) {
      $abscissa_series[] = $key;
    }
  }

  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);



  $palette = NULL;


  $myPicture = new pImage(700, 250, $MyData);


  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 699, 249, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 650, 210);

  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => TRUE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_START0,
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(350, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));

  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  /* Draw the chart */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplayValues" => TRUE,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
          //"InnerSurrounding" => 100,
  );

  if ($color_field) {
    $settings["OverrideColors"] = $palette;
  } else {
    $settings["Gradient"] = TRUE;
    $settings["GradientMode"] = GRADIENT_SIMPLE;
  }
  $myPicture->drawBarChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

function _pi_chart_draw_plot_chart($title, $headers, $grouped_rows) {
  /* Create and populate the pData object */
  $MyData = new pData();

  /**
   * simple processing: one serie per value.
   */
  $series_counter = 1;
  $keys = array_keys($grouped_rows);

  for ($field = 1; $field < count($headers); $field++) {
    for ($key_index = 0; $key_index < count($keys); $key_index++) {
      $row_group = $grouped_rows[$keys[$key_index]];
      usort($row_group, function($a, $b) {
                if ($a[$field] < $b[$field]) {
                  return 1;
                } else if ($a[field] > $b[field]) {
                  return -1;
                } else {
                  return 0;
                }
              });

      foreach ($row_group as $row) {
        $value = $row[$field];
        $series = $key_index > 0 ? array_fill(0, $key_index, VOID) : array();
        $series[] = $value !== NULL ? $value : VOID;
        if ($key_index < count($keys) - 1) {
          $series = array_merge($series, array_fill(0, count($keys) - 1 - $key_index, VOID));
        }
        $MyData->addPoints($series, $series_counter);

        $MyData->setPalette($series_counter, array("R" => 0, "G" => 200, "B" => 0, "Alpha" => 127));


        $series_counter++;
      }
    }
    $MyData->setAxisName(0, $headers[$field]);
  }

  $abscissa_series = array();
  for ($key_index = 0; $key_index < count($keys); $key_index++) {
    $abscissa_series[] = $keys[$key_index];
  }
  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);


  $myPicture = new pImage(700, 250, $MyData);

  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 699, 249, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 650, 210);

  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => TRUE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_START0,
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(350, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));
  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplayValues" => TRUE,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
      "BorderSize" => 2,
      "PlotSize" => 7,
      "PlotBorder" => TRUE,
  );

  $myPicture->drawPlotChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

function _pi_chart_draw_scatter_chart($title, $headers, $rows) {
  /* Create and populate the pData object */
  $myData = new pData();

  $maxX = 0;
  $maxY = 0;

  $count = 0;

  foreach ($rows as $row) {
    if (strlen($row[0]) > 0 && strlen($row[1])) {

      $x = floatval($row[0]);
      $y = floatval($row[1]);
      $maxX = max($maxX, $x);
      $maxY = max($maxY, $y);

      $xid = "X-$count";
      $yid = "Y-$count";
      $myData->addPoints($x, $xid);
      $myData->addPoints($y, $yid);
      $myData->setSerieOnAxis($xid, 0);
      $myData->setSerieOnAxis($yid, 1);
      $myData->setScatterSerie($xid, $yid, $count);
      $myData->setSerieOnAxis($count, 1);

      $myData->setScatterSerieColor($count, array("R" => 200, "G" => 200, "B" => 200, "Alpha" => 0));

      $count++;
    }
  }

  if ($count === 0) {
    $maxX = $maxY = 1;
    $myData->addPoints(array(), "x");
    $myData->addPoints(array(), "y");
    $myData->setSerieOnAxis("x", 0);
    $myData->setSerieOnAxis("y", 1);
    $myData->setScatterSerie("x", "y", 0);
    $myData->setSerieOnAxis(0, 1);
  }

  $myData->setAxisName(0, $headers[0]);
  $myData->setAxisXY(0, AXIS_X);
  $myData->setAxisPosition(0, AXIS_POSITION_BOTTOM);
  $myData->setAxisName(1, $headers[1]);
  $myData->setAxisXY(1, AXIS_Y);
  $myData->setAxisPosition(1, AXIS_POSITION_LEFT);


  $myPicture = new pImage(700, 360, $myData);

  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 699, 359, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 650, 310);

  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => TRUE,
      "Mode" => SCALE_MODE_MANUAL,
      "ManualScale" => array(0 => array("Min" => 0, "Max" => $maxX), 1 => array("Min" => 0, "Max" => $maxY))
  );
  //$myPicture->drawScale($scaleSettings);
  $myPicture->drawText(350, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));
  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));


  $myScatter = new pScatter($myPicture, $myData);
  $myScatter->drawScatterScale($scaleSettings);

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));


  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplayValues" => TRUE,
      "DisplayR" => 65,
      "DisplayG" => 65,
      "DisplayB" => 65,
      //   "DisplayShadow" => TRUE,
      "Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
      "BorderSize" => 2,
      "PlotSize" => 7,
      "PlotBorder" => TRUE,
  );

  if ($count > 0) {
    $myScatter->drawScatterPlotChart($settings);
  }
  /* Draw the legend */
  //$myScatter->drawScatterLegend(280, 380, array("Mode" => LEGEND_HORIZONTAL, "Style" => LEGEND_NOBORDER));

  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

