<?php
// $Id: pi_hypothesis_conclusion.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_hypothesis_conclusion" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_hypothesis_conclusion_node_info() {

    return array(
    'pi_hypothesis_conclusion' => array(
    'name' => t('Inquiry hypothesis conclusion'), // Required.
    'module' => 'pi_hypothesis_conclusion',  // Required.
    'description' => t('What is your conclusion?'), // Required.
    'has_title' => TRUE,
    'title_label' => t('Inquiry hypothesis conclusion'),
    'has_body' => TRUE,
    'body_label' => t('Conclusion'),
    'locked' => TRUE)
    );

}


/**
 * Implementation of hook_perm().
 */

function pi_hypothesis_conclusion_perm() {
    return array('create pi_hypothesis_conclusion content', 'edit pi_hypothesis_conclusion');
}

/**
 * Implementation of hook_access().
 */
function pi_hypothesis_conclusion_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_hypothesis_conclusion'));
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    //return (user_access('edit own pi_hypothesis_conclusion'));
    }
}

/**
 * Implementation of hook_form().
 */

function pi_hypothesis_conclusion_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_hypothesis_conclusion_node_info().


  $details = get_inquiry_details_from_current_path();
  
  if ($details->activity_id) {
  	$current_activity = load_activity($details->activity_id);
  }
  
  if ($current_activity->name) {
  	drupal_set_title(t($current_activity->name));
  }
  else {
  	drupal_set_title(t('Conclusion'));
  }


    global $user;
    $type = node_get_types('type', $node);
    
    
    

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );

    $form['conclusion'] = array(
        '#type' => 'textarea',

        '#required' => TRUE,
        '#default_value' => $node->conclusion,
        '#description' => t('Type your answer into the above box and click on the Save button when you are finished'),
        '#resizable' => FALSE,
        '#rows' => 8,
        '#cols' => 40,
        '#weight' => -2
    );

    $prefix = "";

    $node_details = get_inquiry_details_from_current_path();
    $hypothesis_node_nids = get_node_ids_for_activity_type ($node_details->inquiry_id, 'pi_hypothesis', $user->uid);

    while ($hypothesis_node_nid = db_fetch_object($hypothesis_node_nids)) {
        $hypothesis_node = node_load($hypothesis_node_nid->nid);
        $prefix .= "<p><strong>Your hypothesis was</strong>: " . $hypothesis_node->hypothesis . "</p>";
    };
    
    
  if ($current_activity->description) {
  	$prefix = "<p>" . t($current_activity->description) . "</p>";  
  }
  else {
    $prefix = "<p>" . t('Our conclusion') . "</p>";
  }

    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_hypothesis_conclusion_insert($node) {
    db_query("INSERT INTO {pi_hypothesis_conclusion} (nid, vid, conclusion) VALUES ('%d', '%d', '%s')",
        $node->nid, $node->vid, $node->conclusion);
}

/**
 * Implementation of hook_update().
 */

function pi_hypothesis_conclusion_update($node) {
    if ($node->revision) {
        pi_hypothesis_conclusion_insert($node);
    }

    else {
        db_query("UPDATE {pi_hypothesis_conclusion} SET conclusion = '%s' WHERE vid = %d", $node->conclusion, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_hypothesis_conclusion_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_hypothesis_conclusion} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_hypothesis_conclusion_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_hypothesis_conclusion} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_hypothesis_conclusion_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_hypothesis_conclusion'] = array(
            '#value' => theme('pi_hypothesis_conclusion', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_hypothesis_conclusion_theme() {
    return array(
    'pi_hypothesis_conclusion' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_hypothesis_conclusion($node) {

    $output = '<p><strong>Your conclusion is:</strong> ' . check_plain($node->conclusion). '</p>';

    return $output;
}

