<?php

/**
 * Implementation of hook_install(): registers the VM with
 * the authoring tool.
 */
function vm_designer_install() {
  inquiry_available_tools_register('vm', 'vm_designer');
  inquiry_available_measures_register('vm_length', 'vm_designer', 'vm');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function vm_designer_uninstall() {
  inquiry_available_tools_forget('vm');
}

