<?php
// $Id: ag.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $

/**
 * @file
 * Implements block for Activity Guide navigation.
 */
 
 /**  and n.uid = %d' $uid,
 * Implementation of hook_block().
 */


function build_link($first, $second, $third, $inquiry_id = 0, $stage_id = 0, $phase_id = 0, $activity_id = 0) {
	if (! $activity_id) {
		return t($first . "/" . $second . "/" . $third . "/" . $inquiry_id . "/" . $stage_id . "/" . $phase_id);
	}
	else {
		return t($first . "/" . $second . "/" . $third . "/" . $inquiry_id . "/" . $stage_id . "/" . $phase_id . "/" . $activity_id);
	}
}

function build_home_link($inquiry_id, $stage_id, $phase_id, $activity_id) {
	return t("home///" . $inquiry_id . "///");
	//return t("home///" . $inquiry_id . "/" . $stage_id . "/" . $phase_id . "/" . $activity_id);
}

function build_activity_link($inquiry_id, $stage_id, $phase_id, $activity_id, $uid) {
	
	$image_path = "images/";
	$status_image = array();
	$status_image["start"] = "creatable.png";
	$status_image["edit"] = "editable.png";
	$status_image["view"] = "viewable.png";
	$status_image["unavailable"] = "unavailable.png";
	
	$loaded_activity = load_activity($activity_id);
	$params = $loaded_activity->parameters;
					
	//get node_function and visible_status for inuiqry, activity, uid, gid
	$visible_status = get_visible_status_of_activity ($inquiry_id, $activity_id, $uid);
	$node_function = get_node_function_of_activity ($inquiry_id, $activity_id, $uid);
	
	switch ($loaded_activity->destination) {
    case "self":
		$destination = "";
        break;
    case "phase":
		$destination = t("destination=" . build_link("phase", $phase_id, "view", $inquiry_id, $stage_id, $phase_id,$activity_id));
        break;
    default:
		$destination = t("destination=" . build_home_link($inquiry_id, $stage_id, $phase_id, $activity_id));
        break;
	}
	
	$teacher_gid = check_teacher_activity_for_inquiry_activity_user ($inquiry_id, $activity_id, $uid);
	
	if ($visible_status == "unavailable") {
		$output = t("<img src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>");
	}
	elseif ($node_function == "add") {
		$link = build_link("node", $node_function, str_replace("_", "-", $loaded_activity->node_type), $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}	
		$output = l(t("<img src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>"), $link,  array(html => true, query => $destination));
	}
	else {
		$nid = get_nid_for_inquiry_activity_and_user($inquiry_id, $activity_id, $uid);
		//$nid = get_nid_for_inquiry_activity_and_user(1, 3, 1);
		$link = build_link("node", $nid, $node_function, $inquiry_id, $stage_id, $phase_id, $activity_id);
		if ($params) {
			$link = $link . "/" . $params;
		}
		$output = l(t("<img src=\"" . $image_path. $status_image[$visible_status] . "\"/>" . " " . "<span style='vertical-align: 10%;'>" . $loaded_activity->name . teacher_only_flag($teacher_gid) . "</span>"), $link,  array(html => true, query => $destination));
	}
	
	return $output;
}

function ag_block($op = 'list', $delta = 0, $edit = array()) {
	
	switch ($op) {
  
    case 'list':
		$blocks[0]['info'] = t('New Activity Guide');
		return $blocks;
    
    case 'view':

		global $user;
		$image_path = "images/";
		$node_details = get_inquiry_details_from_current_path();

		$phases = get_phases_of_inquiry_and_user($node_details->inquiry_id, $user->uid);
		
		$current_stage = get_current_stage_of_inquiry_and_user($node_details->inquiry_id, $user->uid);		
		$current_stage_id = $current_stage->stage_id;
		
		$current_stage_phases = get_phases_of_stage ($node_details->inquiry_id, $current_stage_id);
		
		$phases_of_current_stage = array();
		while ($phase_of_current_stage = db_fetch_object($current_stage_phases)) {
			$phases_of_current_stage[] =  $phase_of_current_stage->phase_id;
		}
		
		$phase_menu_items = array();
		
		while ($phase = db_fetch_object($phases)) {
			$loaded_phase = load_phase($phase->phase_id);
			$teacher_gid = check_teacher_phase_for_inquiry_phase_user ($node_details->inquiry_id, $phase->phase_id, $user->uid);
			
			
			if (in_array($phase->phase_id, $phases_of_current_stage)) {
				$diplayed_phase_name = t("<div style=\"border: 0px; background-color:#aaaaaa;\">" . "<img src=\"" . $image_path . "folder_empty_current.png\" style=\"margin: 0.4em 0 0 0.2em;\"/><span style='vertical-align: 20%;'>&nbsp;&nbsp;" . $loaded_phase->name . teacher_only_flag($teacher_gid) . "</span></div>");
			}
			else {
				$diplayed_phase_name = t("<div style=\"border: 0px; background-color:#d2d2d2;\">"  . "<img src=\"" . $image_path . "folder_empty.png\" style=\"margin: 0.4em 0 0 0.2em;\"/><span style='vertical-align: 20%;'>&nbsp;&nbsp;" . $loaded_phase->name . teacher_only_flag($teacher_gid) . "</span></div>");
			}			

			$phase_link = l($diplayed_phase_name, build_link("phase", $phase->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $phase->phase_id, $node_details->activity_id), array(html => true));
			
			$activity_menu_items = array();
			//expand activities of the phase if it is current
			if ($phase->phase_id == $node_details->phase_id) {
				//$activities = get_activities_of_stage_phase_and_user(1, NULL, NULL, 1);
				$activities = get_activities_of_stage_phase_and_user($node_details->inquiry_id, NULL, $phase->phase_id, $user->uid);
				foreach($activities as $activity) {
					
					$activity_menu_items[] = build_activity_link($node_details->inquiry_id, $node_details->stage_id, $phase->phase_id, $activity->activity_id, $user->uid);
				}
			}
			
			$phase_menu_items[] = array(data => $phase_link, children => $activity_menu_items);
			
		}
		
		$home_link = build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

		
		$block['subject'] = l(t("Inquiry Guide&nbsp;" . "<img src=\"" . $image_path . "home.png\"/>"), t($home_link), array(html=>true));
		
		$block_content = t(theme('item_list', $phase_menu_items));
		
		$block['content'] = "<div class='activity-guide'>" . $block_content . "</div>";
	
		return $block;
	};
}

function teacher_only_flag ($gid) {
	if ($gid) {
		return " (T)";
	}
	else {
		return "";
	}
}