<?php

function inquiry_activity_editor_create_activity_stub($type, $title) {
  $node = new stdClass();
  $node->type = 'inquiry_activity';
  $node->activity_type = $type;
  $node->title = $title;

  node_save($node);
  return $node;
}

/**
 * Utility function that creates form items to edit the 
 * 
 * @param type $form Form to be modified.
 */
function inquiry_activity_editor_add_title_body_form_items(&$form, $node) {
  
}



function inquiry_activity_editor_activity_form(&$form_state, $design, $node) {
  $form = array();

  _inquiry_creator_create_inquiry_id_form_item($design, $form);
  $form['activity_id'] = array(
      '#type' => 'hidden',
      '#default_value' => $node->nid,
      '#required' => TRUE,
  );

  $type = node_get_types('type', $node);

  $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#description' => t('Write here the activity title.'),
      '#required' => TRUE,
      '#default_value' => $node->title,
  );

  //Show a simple textarea, no input selector required....
  $form['body_filter']['body'] = array(
      '#type' => 'textarea',
      '#title' => check_plain($type->body_label),
      '#description' => t('Write here the instructions for the inquiry participants. This should describe their tasks in this activity.'),
      '#default_value' => $node->body,
      '#required' => TRUE
  );

  _inquiry_creator_create_form_buttons('inquiry_activity_editor_activity_form_submit', $form, $design);

  return $form;
}


function inquiry_activity_editor_activity_form_submit($form, $form_state) {
  inquiry_creator_form_cancel($form, $form_state);
}

