<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_activity_editor_install() {
  inquiry_available_activities_register('notes', 'inquiry_activity_editor');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_activity_editor_uninstall() {
  inquiry_available_activities_forget('notes');
}

