<?php




function inquiry_activity_editor_create_activity_stub($type, $title) {
  $node = new stdClass();
  $node->type = 'inquiry_activity';
  $node->activity_type = $type;
  $node->title = $title;
  
  node_save($node);
  return $node;
}

/**
 * Utility function that creates form items to edit the 
 * 
 * @param type $form Form to be modified.
 */
function inquiry_activity_editor_add_title_body_form_items(&$form, $node) {
  
}

function inquiry_activity_editor_activity_form(&$form, $design, $node) {
  return "hey!";
}
function inquiry_activity_editor_activity_form_submit($form, $form_state) {
  
}


