<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_measures_designer_install() {
  inquiry_available_features_register('measure', '_number', 'inquiry_basic_measures_designer');
  inquiry_available_features_register('measure', '_text', 'inquiry_basic_measures_designer');
  inquiry_available_features_register('measure', '_options', 'inquiry_basic_measures_designer');
  inquiry_available_features_register('measure', '_image', 'inquiry_basic_measures_designer');
  inquiry_available_features_register('measure', '_date', 'inquiry_basic_measures_designer');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_measures_designer_uninstall() {
  inquiry_available_features_forget('measure', '_number');
  inquiry_available_features_forget('measure', '_text');
  inquiry_available_features_forget('measure', '_options');
  inquiry_available_features_forget('measure', '_image');
  inquiry_available_features_forget('measure', '_date');
}

