<?php
// $Id: pi_pond_hypothesis.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "hypothesis" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_pond_hypothesis_node_info() {
  return array(
	'pi_pond_hypothesis' => array(
      	 'name' => t('Pond Inquiry hypothesis'), // Required.
	 'module' => 'pi_pond_hypothesis',  // Required.
	 'description' => t('What is your inquiry question?'), // Required.
	 'has_title' => TRUE,
	 'title_label' => t('Hadden Park Pond Life inquiry'),
	 'has_body' => TRUE,
	 'body_label' => t('Hypothesis'),
	 'min_word_count' => 2,
	 'locked' => TRUE
	)
   );
}


/**
 * Implementation of hook_perm().
 */

function pi_pond_hypothesis_perm() {
  return array('create pi_pond_hypothesis content', 'edit pi_pond_hypothesis');
}

/**
 * Implementation of hook_access().
 */
function pi_pond_hypothesis_access($op, $node) {
  global $user;

  if ($op == 'create') {
    return TRUE;
  }

  if ($op == 'update' || $op == 'delete') {
    return TRUE;
  }
}

/**
 * Implementation of hook_form().
 */

function pi_pond_hypothesis_form(&$node) {

  // Get metadata for this node type
  // (we use it for labeling title and body fields).
  // We defined this in pi_pond_hypothesis_node_info().
  $type = node_get_types('type', $node);

  $form['title'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->title_label),
    '#required' => FALSE,
    '#default_value' => check_plain($type->title_label),
    '#weight' => -5
  );

  $form['textarea_fieldset'] = array(
    '#type' => 'fieldset'
  );
  
  $form['textarea_fieldset']['hypothesis'] = array(
    '#type' => 'textarea',
    '#title' => t('My inquiry question is '),
    '#required' => TRUE,
    '#default_value' => $node->hypothesis,
    '#resizable' => FALSE,
    '#rows' => 2,
    '#cols' => 40,
    '#weight' => 2
  );
  

  
  $prefix .= "<p>An inquiry question is a prediction that you can test.</p>";
  $prefix .= "<p>Based on the discussion you had in class, think about what a good inquiry question would be</p>";
  $prefix .= "<p>Write your inquiry question here</p>";
 
  $form['#prefix'] = $prefix;
  
  return $form;

}

/**
 * Implementation of hook_insert().
 */

 
function pi_pond_hypothesis_insert($node) {
  db_query("INSERT INTO {pi_pond_hypothesis} (nid, vid, hypothesis) VALUES (%d, %d,'%s')",
    $node->nid, $node->vid, $node->hypothesis);
}

/**
 * Implementation of hook_update().
 */

function pi_pond_hypothesis_update($node) {
  if ($node->revision) {
    pi_pond_hypothesis_insert($node);
  }
  
  else {
    db_query("UPDATE {pi_pond_hypothesis} SET hypothesis = '%s' WHERE vid = %d", $node->hypothesis,  $node->vid);
  }
}

/**
 * Implementation of hook_delete().
 */

function pi_pond_hypothesis_delete(&$node) {
  // Delete the related information we were saving for this node.
  db_query('DELETE FROM {pi_pond_hypothesis} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_pond_hypothesis_load($node) {
  return db_fetch_object(db_query('SELECT * FROM {pi_pond_hypothesis} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_pond_hypothesis_view($node, $teaser = FALSE, $page = FALSE) {
  if (!$teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);

    $node->content['pi_pond_hypothesis'] = array(
    '#value' => theme('pi_pond_hypothesis', $node),
    '#weight' => 2
    );
      
  }

  if ($teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);
  }

  return $node;
}

function pi_pond_hypothesis_theme() {
  return array(
    'pi_pond_hypothesis' => array(
      'arguments' => array('node'),
    ),
  );
}


function theme_pi_pond_hypothesis($node) {
  $output = '<div class="pi_pond_hypothesis">Your inquiry question is: ' . check_plain($node->hypothesis). '</div><br />';
  
  return $output;
}

