<?php

/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_measures_install() {
  pi_available_measures_plugins_register_measure_type('_text', 'inquiry_basic_measures');
  pi_available_measures_plugins_register_measure_type('_number', 'inquiry_basic_measures');
  pi_available_measures_plugins_register_measure_type('_options', 'inquiry_basic_measures');
  pi_available_measures_plugins_register_measure_type('_image', 'inquiry_basic_measures');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_measures_uninstall() {
  pi_available_measures_plugins_forget_measure_type('_text');
  pi_available_measures_plugins_forget_measure_type('_number');
  pi_available_measures_plugins_forget_measure_type('_options');
  pi_available_measures_plugins_forget_measure_type('_image');
}

