<?php

/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_measures_install() {
  pi_data_tools_measure_plugins_register_type('_text', 'inquiry_basic_measures');
  pi_data_tools_measure_plugins_register_type('_number', 'inquiry_basic_measures');
  pi_data_tools_measure_plugins_register_type('_options', 'inquiry_basic_measures');
  pi_data_tools_measure_plugins_register_type('_image', 'inquiry_basic_measures');
  pi_data_tools_measure_plugins_register_type('_date', 'inquiry_basic_measures');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_measures_uninstall() {
  pi_data_tools_measure_plugins_forget_type('_text');
  pi_data_tools_measure_plugins_forget_type('_number');
  pi_data_tools_measure_plugins_forget_type('_options');
  pi_data_tools_measure_plugins_forget_type('_image');
  pi_data_tools_measure_plugins_forget_type('_date');
}

