<?php

/**
 * Implementation of pi_fooddiary_install().
 */
function pi_foodinfo_install()
{
	// Create tables.
	drupal_install_schema('pi_foodinfo');
	variable_set('og_content_type_usage_pi_foodinfo', 'group_post');
	//Options are status, promote, sticky, revision
	variable_set("node_options_pi_foodinfo", array('status','revision'));
	variable_set("comment_pi_foodinfo", COMMENT_NODE_DISABLED);
	variable_set('upload_pi_foodinfo', 0);
	
	drupal_set_message( 'You need to set the permissions for the Food Info module!', 'error' );
}

/**
 * Implementation of pi_fooddiary_uninstall().
 */
function pi_foodinfo_uninstall()
{
	// Remove tables.
	drupal_uninstall_schema('pi_foodinfo');
	variable_del('og_content_type_usage_pi_foodinfo');
	variable_del("node_options_pi_foodinfo");
	variable_del("comment_pi_foodinfo");
	variable_del('upload_pi_foodinfo');
}

/**
 * Implementation of pi_fooddiary_schema().
 */
function pi_foodinfo_schema()
{
	$schema = array();
	
	$schema['pi_foodinfo'] = array(
    	'description' => t('Fooddiary data'),
    	'fields' => array(
	  		'chid' => array(
        			'description' => t('id'),
        			'type' => 'serial',
					'not null' => TRUE
				),
      		'nid' => array(
    	    		'description' => t('Node id'),
       	 			'type' => 'int',
					'unsigned' => TRUE,
       				'not null' => TRUE,
					'size' => 'medium',
					'default' => 0,
				),
      		'vid' => array(
        			'description' => t('The current vid version identifier'),
					'type' => 'int',
					'unsigned' => TRUE,
					'not null' => TRUE,
					'size' => 'medium',
					'default' => 0,
				),
      		'description' => array(
        			'description' => t('Food description'),
        			'type' => 'text',
        			'size' => 'normal',
        			'not null' => FALSE,
				),				
      		'portion' => array(
        			'description' => t('Food portion'),
        			'type' => 'text',
        			'size' => 'normal',
        			'not null' => FALSE,
				),
      		'carb' => array(
        			'description' => t('Carb'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'protein' => array(
        			'description' => t('Protein'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'fats' => array(
        			'description' => t('Fat'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'fibre' => array(
        			'description' => t('Fibre'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'water' => array(
        			'description' => t('Water'),
        			'type' => 'int',
					'unsigned' => TRUE,
					'not null' => TRUE,
					'size' => 'medium',
					'default' => 0,
				),
			'sodium' => array(
        			'description' => t('Sodium'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'calcium' => array(
        			'description' => t('Calcium'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'iron' => array(
        			'description' => t('Iron'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'vita' => array(
        			'description' => t('Vitamin A'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'vitb' => array(
        			'description' => t('Vitamin B'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
      		'vitc' => array(
        			'description' => t('Vitamin C'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
			'vitd' => array(
        			'description' => t('Vitamin D'),
        			'type' => 'int',
        			'unsigned' => TRUE,
        			'not null' => TRUE,
        			'size' => 'medium',
        			'default' => 0,
				),
			),
		'primary key' => array('chid'),
    	'indexes' => array(
				'chid' => array('chid'),
      			'nid' => array('nid'),
      			'vid' => array('vid'),
			)
		);

	return $schema;
}