<?php

function pi_journal_menu() {

	$items = array();

	$items['journal'] = array(
			'title' => 'Inquiry results',
			'page callback' => 'pi_journal_home',
			'type' => MENU_CALLBACK,
			'access callback' => 'pi_journal_page_access',
	);

	$items['journal/inquiry/%'] = array(
			'title' => 'Inquiry results',
			'page callback' => 'pi_journal_inquiry_page',
			'page arguments' => array(2),
			'type' => MENU_CALLBACK,
			'access callback' => 'pi_journal_page_access',
	);

	$items['journal/contribution/%'] = array(
			'title' => 'Inquiry results',
			'page callback' => 'pi_journal_contribution_page',
			'page arguments' => array(2),
			'type' => MENU_CALLBACK,
			'access callback' => 'pi_journal_page_access',
	);


	return $items;
}

function pi_journal_page_access() {
	return TRUE;
}

function pi_journal_home() {
	return theme('pi_journal_list', pi_journal_contributions_find_all_shared_contributions(), TRUE);
}

function pi_journal_inquiry_page($inquiry_id) {
	return theme('pi_journal_list', pi_journal_contributions_find_shared_contributions_for_inquiry($inquiry_id), FALSE);
}

function pi_journal_contribution_page($node_id) {
	$node = node_load($node_id);
	if ($node->type === 'pi_journal_contribution' && $node->shared) {
		return theme('pi_journal_contribution_display', $node);
	}
}

function pi_journal_theme() {
	return array(
			'pi_journal_list' => array(
					'arguments' => array('items' => NULL, 'inquiry_page_links' => FALSE),
			),
			'pi_journal_results' => array(
					'arguments' => array('item' => NULL),
			),
			'pi_journal_share_information' => array(
					'arguments' => array('inquiry_node' => NULL),
			),
	);
}

function pi_journal_edit_share_access($inquiry_node) {
	global $user;
	switch (pi_inquiry_groupings_get_coarser_collaboration_level($inquiry_node->nid)) {
		case 'individual':
			return nquire_group_get_user_status_in_group($inquiry_node->actor_gid, $user->uid) === 'member';
		case 'group':
			$subgroup = node_load(pi_inquiry_groupings_get_user_subgroup($inquiry_node, $user->uid));
			return $subgroup && $subgroup->uid === $user->uid;
		case 'all':
			return $inquiry_node->uid === $user->uid;
		default:
			return FALSE;
	}
}

function pi_journal_edit_share_investigation($inquiry_node, $uid, $publish, $title, $summary) {
	$contribution_nid = pi_journal_contribution_find_contribution_nid($inquiry_node, $uid);
	$node = node_load($contribution_nid);
	$collaboration = pi_inquiry_groupings_get_coarser_collaboration_level($inquiry_node->nid);
	$actor = pi_inquiry_groupings_get_actor_for($inquiry_node, $collaboration, $uid);

	if (!$node && $publish) {
		$node = new stdClass();
		$node->type = 'pi_journal_contribution';
		$node->uid = $uid;
		$node->inquiry_id = $inquiry_node->nid;
		$node->actor = $actor;
		$node->collaboration = $collaboration;
		$node->comment = COMMENT_NODE_READ_WRITE;
	}

	$node->shared = $publish;
	$node->title = $title;
	$node->body = $summary;

	node_save($node);
}

function theme_pi_journal_share_information($inquiry_node) {
	global $user;

	$access = pi_journal_edit_share_access($inquiry_node);
	$contribution_node = pi_journal_contribution_find_contribution_node($inquiry_node, $user->uid);

	if ($contribution_node->shared) {
		$link = '<br/>' . t('Click <a href="@url">here</a> to view it. ', array('@url' => url('journal/contribution/' . $contribution_node->nid)));
	}

	$all = '<br/>' . t('You can see all the published investigations <a href="@url">here</a>. ', array('@url' => url('journal')));

	$output = '<p>';

	switch ($contribution_node->collaboration) {
		case 'individual':
			if ($contribution_node->shared) {
				$output .= t('You have published your individual investigation. ') . $link . $all;
			} else {
				$output .= t('You have not published you individual investigation. ') . $all;
			}
			break;
		case 'group':
			if ($access) {
				if ($contribution_node->shared) {
					$output .= t('You have published the results of your group investigation. ') . $link . $all;
				} else {
					$output .= t('You have not published the results of your group investigation. ') . $all;
				}
			} else {
				if ($contribution_node->shared) {
					$output .= t('The group owner has published the results of your investigation. ') . $link . $all;
				} else {
					$output .= t('The group owner has not published the results of this investigation. ') . $all;
				}
			}
			break;
		case 'all':
			if ($access) {
				if ($contribution_node->shared) {
					$output .= t('You have published the results of this inquiry. ') . $link . $all;
				} else {
					$output .= t('You have not published the results of this inquiry. ') . $all;
				}
			} else {
				if ($contribution_node->shared) {
					$output .= t('The inquiry owner has published the results of the investigation. ') . $link . $all;
				} else {
					$output .= t('The inquiry owner has not published the results of the investigation. ') . $all;
				}
			}
			break;
	}

	$output .= '</p>';
	return $output;
}

function theme_pi_journal_list($items, $inquiry_page_links) {
	$output = '';
	foreach ($items as $inquiry_nid => $contributions_data) {
		$inquiry = node_load($inquiry_nid);
		if ($inquiry_page_links) {
			$url = url('journal/inquiry/' . $inquiry_nid, array('absolute' => TRUE));
			$inquiry_title_text = t('Investigations for <a href="@url"><i>@inquiry</i></a>:', array('@inquiry' => $inquiry->title, '@url' => $url));
		} else {
			$inquiry_title_text = t('Investigations for <i>@inquiry</i>:', array('@inquiry' => $inquiry->title));
		}

		$output .= '<h3>' . $inquiry_title_text . '</h3>';

		$formatted_inquiry_items = array_map(function($node) {
							return theme('pi_journal_contribution_teaser', $node, $inquiry);
						}, $contributions_data['contributions']);
		$output .= theme('item_list', $formatted_inquiry_items);
	}

	return $output;
}
