<?php

/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function nutritional_information_measure_install() {
  pi_data_tools_measure_plugins_register_type('_nutritionalinformation', 'nutritional_information_measure');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function nutritional_information_measure_uninstall() {
  pi_data_tools_measure_plugins_forget_type('_nutritionalinformation');
}

