<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_measures_install() {
  inquiry_available_features_register('measure', '_number', 'inquiry_basic_measures');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_measures_uninstall() {
  inquiry_available_features_forget('measure', '_number');
}

