<?php


/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_measures_install() {
  inquiry_available_measures_register('_number', 'inquiry_basic_measures', 'none');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_measures_uninstall() {
  inquiry_available_measures_forget('_number');
}

