<?php
// $Id: pi_about_birddata.module,v 1.0 2009/11/24 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_about_birddata" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_about_birddata_node_info() {

    return array(
    'pi_about_birddata' => array(
    'name' => t('About Birds data'), // Required.
    'module' => 'pi_about_birddata',  // Required.
    'description' => t('About Birds data'), // Required.
    'has_title' => TRUE,
    'title_label' => t('Reflections on your data collection'),
    'has_body' => FALSE,
    'body_label' => t('Reflections on your data collection'),
    'locked' => TRUE)
    );

}


/**
 * Implementation of hook_perm().
 */

function pi_about_birddata_perm() {
    return array('create pi_about_birddata content', 'edit pi_about_birddata');
}

/**
 * Implementation of hook_access().
 */
function pi_about_birddata_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    }
}

/**
 * Implementation of hook_form().
 */

function pi_about_birddata_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_about_birddata_node_info().
    $type = node_get_types('type', $node);
  	global $user;
  
  	$node_details = get_inquiry_details_from_current_path();
  	if (is_numeric($node_details->activity_id)) {
  		$current_activity = load_activity($node_details->activity_id);
  	}
  	
  	if ($current_activity->name) {
  		drupal_set_title(t($current_activity->name));
  	}

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );

    $form['problems'] = array(
        '#type' => 'textarea',
        '#title' => t('What problems did you have during your data gathering?'),
        '#required' => FALSE,
        '#default_value' => $node->problems,
        '#description' => t('Type in any problems you had while you gathered data'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -4
    );
    $form['meaning'] = array(
        '#type' => 'textarea',
        '#title' => t('What does your data mean?'),
        '#required' => FALSE,
        '#default_value' => $node->meaning,
        '#description' => t('Type in what you think your data means'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -3
    );

    $prefix = "";

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>About bird data reflection.</p>";
    }
*/
    
    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_about_birddata_insert($node) {
    db_query("INSERT INTO {pi_about_birddata} (nid, vid, problems, meaning) VALUES ('%d', '%d', '%s', '%s')",
        $node->nid, $node->vid, $node->problems, $node->meaning);
} 

/* Implementation of hook_update().
 */

function pi_about_birddata_update($node) {
    if ($node->revision) {
        pi_about_noise_insert($node);
    }

    else {
        db_query("UPDATE {pi_about_birddata} SET problems = '%s', meaning = '%s'  WHERE vid = %d", $node->problems, $node->meaning, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_about_birddata_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_about_birddata} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_about_birddata_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_about_birddata} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_about_birddata_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_about_birddata'] = array(
            '#value' => theme('pi_about_birddata', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_about_birddata_theme() {
    return array(
    'pi_about_birddata' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_about_birddata($node) {

    $output = '<p><strong>What problems did you have during your data gathering?</strong> ' . check_plain($node->problems). '</p>';
    $output .= '<p><strong>What does your data mean?</strong> ' . check_plain($node->meaning). '</p>';
 
    return $output;
}

