<?php

// $Id: ag.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $


function pi_my_inquiries_block($op = 'list') {

	switch ($op) {
		case 'list':

			$blocks = array(
					array('info' => t('My inquiries'))
			);

			return $blocks;

		case 'view':
			global $user;
			$block = array();

			if ($user->uid && arg(0) !== 'inquiries' && !pi_info()->getCurrentInquiryInfo()) {
				$block['subject'] = l(t('My inquiries'), 'inquiries');

				$inquiry_groups = pi_inquiry_groupings_get_groups_for_user($user->uid, NQUIRE_GROUP_TYPE_INQUIRY);
				$joined_inquiries = pi_inquiry_groupings_get_inquiries_for_groups($inquiry_groups['active']);

				if (count($joined_inquiries) > 0) {
					$list = array_map(function($nid) {
										$node = node_load($nid);
										return l(check_plain($node->title), "inquiry/$nid/structure");
									}, $joined_inquiries);
					$block['content'] = theme('item_list', $list);
				} else {
					$block['content'] = t('You have not joined any inquiry yet.');
				}
			}
			return $block;
	}
}

