<?php

function pi_profile_menu() {

  $items = array();

  $items['profile/%'] = array(
      'title' => 'My profile',
      'page callback' => 'pi_profile_home',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'pi_profile_page_access',
      'access arguments' => array(1),
  );

  $items['profile/%/edit'] = array(
      'title' => 'Edit my profile',
      'page callback' => 'pi_profile_edit',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'pi_profile_page_access',
      'access arguments' => array(1),
  );

  $items['profile/%/events'] = array(
      'title' => 'Events',
      'page callback' => 'pi_profile_events',
      'page arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'pi_profile_page_access',
      'access arguments' => array(1),
  );


  return $items;
}

function pi_profile_page_access($uid) {
  global $user;
  return $user->uid === $uid;
}

function pi_profile_home() {
  global $user;
  return "hi {$user->uid}!";
}

function pi_profile_edit() {
  global $user;
  return "edit {$user->uid}!";
}

function pi_profile_events() {
  global $user;
  return "events {$user->uid}!";
}
