<?php


/**
 * 
 * Registers an scientific instrument in the authoring tool so that it ca be ofered 
 * to designers. Modules registering an activity must implement a number of
 * nQuire hooks:
 * 
 *  - [module]_nquire_creator_tool_[type]_form($tool_data, &$form)
 *  - [module]_nquire_creator_tool_[type]_form_process(&$tool_data, $design, $form_values)
 * 
 * @param type $type The tool being registered
 * @param type $module The module that manages the registered activity type
 */
function inquiry_available_tools_register($type, $module) {
  $tools = variable_get('nquire_creator_tool_types', array());
	$tools[$type] = $module;
	variable_set('nquire_creator_tool_types', $tools);
}

function inquiry_available_tools_forget($type) {
  $activities = variable_get('nquire_creator_tool_types', array());
	unset($activities[$type]);
	variable_set('nquire_creator_tool_types', $activities);
}

function inquiry_available_tools_types() {
  return variable_get('nquire_creator_tool_types', array());
}

function inquiry_available_tools_module_for_type($activity_type) {
  $types = inquiry_available_tools_types();
  return isset($types[$activity_type]) ? $types[$activity_type] : FALSE;
}

function inquiry_available_tools_invoke($nquire_creator_hook, $tool_type, &$a = NULL, &$b = NULL, &$c = NULL, &$d = NULL) {
  $module = inquiry_available_tools_module_for_type($tool_type);
  if ($module) {
    $fname = "{$module}_nquire_creator_tool_{$tool_type}_{$nquire_creator_hook}";
    if (function_exists($fname)) {
      return $fname($a, $b, $c, $d);
    }
  }
  
  return FALSE;
}

function inquiry_available_tools_name($tool_type) {
  $name = inquiry_available_tools_invoke('name', $tool_type);
  return $name ? $name : $tool_type;
}
