<?php
// $Id$

/**
 * @file
 * Functions for showing activity list for a phase
 */

/**
 * Show activity list for a phase
 */
function pi_list_activities_for_phase($user, $phase) {
	$destination = "destination=node";
	$uid = $user->uid;
	$uroles = $user->roles;
	$activity_list = array();
	$gid_array = find_gid_array_for_uid ($uid);
	$gid_activity_list = db_query("SELECT pi_activity.name, pi_phase_activity.phase_id, pi_phase_activity.position, pi_activity_actor.activity_id, pi_activity_roles.node_type, pi_activity_roles.node_type_creator_role, pi_activity_roles.node_type_editor_role, pi_activity_roles.node_type_viewer_role, pi_activity_roles.parameters FROM pi_activity, pi_phase_activity, pi_activity_actor,  og_uid, pi_activity_roles WHERE og_uid.uid = %d AND og_uid.nid = pi_activity_actor.gid AND pi_activity_actor.activity_id = pi_activity.activity_id AND pi_activity.activity_id = pi_phase_activity.activity_id AND pi_phase_activity.phase_id = %d AND pi_phase_activity.activity_id = pi_activity_roles.activity_id ORDER BY pi_phase_activity.position", $uid, $phase);
	$uid_activity_list = db_query("SELECT pi_activity.name, pi_phase_activity.phase_id, pi_phase_activity.position, pi_activity_actor.activity_id, pi_activity_roles.node_type, pi_activity_roles.node_type_creator_role, pi_activity_roles.node_type_editor_role, pi_activity_roles.node_type_viewer_role, pi_activity_roles.parameters FROM pi_activity, pi_phase_activity, pi_activity_actor, pi_activity_roles WHERE 
pi_activity_actor.uid = %d AND
pi_activity_actor.activity_id = pi_activity.activity_id AND
pi_activity.activity_id = pi_phase_activity.activity_id AND
pi_phase_activity.phase_id = %d AND
pi_phase_activity.activity_id = pi_activity_roles.activity_id ORDER BY pi_phase_activity.position", $uid, $phase);
	$combined_activities = array();
	while ($activity = db_fetch_object($gid_activity_list)) {
		$combined_activities[] = $activity;
	}
	while ($activity = db_fetch_object($uid_activity_list)) {
		$combined_activities[] = $activity;
	}		
	
	//if (count($combined_activities) > 0) {
	//	print t("<p>This part of the investigation contains the following tasks:</p>");
	//}
	
	$activities = array();
	foreach  ($combined_activities as $activity) {
	
		$activity_node = find_activity_node_for_activity_id_and_uid ($activity->activity_id, $uid);
		if (! $activity_node) {
			$activity_node = find_activity_node_for_activity_id_and_gid_array($activity->activity_id, $gid_array);
		}
		
			if ($activity_node) {
				if (in_array($activity -> node_type_editor_role, $uroles)) {
					//edit status
					$image_tag = "<img src=\"/pi/images/black_doc.jpg\"/>";
					$ag_link = t('node/' . $activity_node . '/edit' . $activity->parameters);
					$ag_status = l($image_tag, $ag_link, array(), $destination, NULL,FALSE,TRUE);
					$activity_name = l(t("<b>" . $activity -> name . "</b>"), $ag_link, array(), $destination, NULL,FALSE,TRUE);
				}
				else
				{
					if (in_array($activity -> node_type_viewer_role, $uroles)) {
						//view status
						$image_tag = "<img src=\"/pi/images/grey_doc.jpg\"/>";
						$ag_link = t('node/' . $activity_node. '/view' . $activity->parameters);
						$ag_status = l($image_tag, $ag_link, array(), $destination, NULL,FALSE,TRUE);
						$activity_name = l(t("<b>" . $activity -> name . "</b>"), $ag_link, array(), $destination, NULL,FALSE,TRUE);
					}
					else
					{
						//there status
						$ag_status = t("<img src=\"/pi/images/grey_empty.jpg\"/>");
						$activity_name = t($activity -> name);
					}
				}
			}
			else
			{
				if(in_array($activity -> node_type_creator_role, $uroles)) {
					//add status
					$image_tag = "<img src=\"/pi/images/black_empty.jpg\"/>";
					$ag_link = t('node/add/' . $activity->node_type . $activity->parameters);
					$ag_status = l($image_tag, $ag_link, array(), $destination, NULL,FALSE,TRUE);
					$activity_name = l(t("<b>" . $activity -> name . "</b>"), $ag_link, array(), $destination, NULL,FALSE,TRUE);
				}
				else
				{
					//not there status
					$ag_status = t("<img src=\"/pi/images/grey_empty.jpg\"/>");
					$activity_name = t($activity -> name);
				}
			}
		

		$activity_description = db_fetch_object(db_query("SELECT description FROM node_type WHERE type = \"%s\" ", $activity->node_type));
		print t("<dl>");
		print t("<dt>" . $ag_status . ' ' . $activity_name . "</dt>");
		print t("<dd>" . $activity_description->description . "</dd>");
		print t("</dl>");
	}
}

