<?php

/**
 * @file pi authoring activity w module
 */

/**
 * Implementation of hook_node_info().
 */
function pi_authoring_activity_w_node_info() {
  // We return an array since a module can define multiple node types.
  // We're only defining one node type, type 'pi_question'.
  return array(
    'pi_authoring_activity_w' => array(
      'name' => t('Tempory Activity Place Holder (wiki)'), // Required.
      'module' => 'pi_authoring_activity_w',  // Required.
      'description' => t('temporary pi authoring activity'), // Required.
      'has_title' => TRUE,
      'title_label' => t('Tempory Activity Place Holder (wiki)'),
      'has_body' => FALSE,
      'locked' => TRUE
    )
  );
}

/**
 * Implementation of hook_perm().
 */
function pi_authoring_activity_w_perm() {
	return array('create pi_authoring_activity', 'edit own pi_authoring_activity');
}

/**
 * Implementation of hook_access().
 */
function pi_authoring_activity_w_access($op, $node) {
  global $user;
  //$details = get_inquiry_details_of_node_path($node->path);
  $details = get_inquiry_details_from_current_path();
  
  if ($op == 'create') {
   return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_authoring_activity'));
  }

  if ($op == 'update' || $op == 'delete') {
    return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
	//return (user_access('edit own pi_authoring_activity') && ($user->uid == $node->uid));
  }
}

/**
 * Implementation of hook_form().
 */
function pi_authoring_activity_w_form($node, $form_state) {
  $type = node_get_types('type', $node);
  $image_path = drupal_get_path('module', 'ag') . '/images';
    
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -5
  );
  
  //this is testing showing the audience type in the node 
  $node_details = get_inquiry_details_from_current_path();
  $activity = load_activity($node_details->activity_id);
  switch ($activity->audience) {
	case "individual":
		$prefix .= t("<img src=\"" . $image_path. "individual_logo.png\" style=\"width: 3em; height: 3em; margin-right:0.2em;\"/>") . "<span style='vertical-align: 90%;'>" . "This is an individual activity" . "</span>";
		break;
	case "group":
		$prefix .= t("<img src=\"" . $image_path. "group_logo.png\" style=\"width: 3em; height: 3em; margin-right:0.2em;\"/>") . "<span style='vertical-align: 90%;'>" . "This is a group activity" . "</span>";
		break;
	case "class":
		$prefix .= t("<img src=\"" . $image_path. "class_logo.png\" style=\"width: 3em; height: 3em; margin-right:0.2em;\"/>") . "<span style='vertical-align: 90%;'>" . "This is a class activity" . "</span>";
		break;		
	}
  
  $prefix .= "<p>Activity: " . arg(7) . ".</p>";
  $prefix .= "path: " . t($node->path);
  $form['#prefix'] = $prefix;
  
  return $form;
}

/**
 * Implementation of hook_insert().
 */
function pi_authoring_activity_w_insert($node) {
  $query = "INSERT INTO authoring_activity SET ";
  $query .= "placeholder_name = '" . $node->title . "' ";
  $query .= ", nid = '" . $node->nid . "'";
  $query .= ", vid = '" . $node->vid . "'";
  db_query($query);
}

/**
 * Implementation of hook_update().
 */
function pi_authoring_activity_w_update($node) {
  if ($node->revision) {
    pi_authoring_activity_w_insert($node);
  }
  
  else {
    $query = "UPDATE authoring_activity SET placeholder_name = '" . $node->title . "'";
    db_query($query);
  }
}

/**
 * Implementation of hook_delete().
 */
function pi_authoring_activity_w_delete(&$node) {
	$query = "DELETE FROM authoring_activity WHERE nid = '" . $node->nid . "'";
  	db_query($query);
}

/**
 * MISSING
 * 
 * @param $node
 * @return unknown_type
 */
function pi_authoring_activity_w_load($node) {
	$query = "SELECT * FROM authoring_activity WHERE vid = '" . $node->vid . "'";
	return db_fetch_object(db_query($query));
}

/**
 * Implementation of hook_view().
 */
function pi_authoring_activity_w_view($node, $teaser = FALSE, $page = FALSE) {
  if (!$teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);

    $node->content['pi_authoring_activity_w'] = array(
    '#value' => theme('pi_authoring_activity_w', $node),
    '#weight' => 2
    );
      
  }

  if ($teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);
  }

  return $node;
}

/**
 * MISSING
 * 
 * @param unknown_type $node
 * @return string
 */
function theme_pi_authoring_activity_w($node) {
  $output = '<div class="pi_authoring_activity_w">' . check_plain($node->title). '</div><br />';
  
  return $output;
}