<?php
// $Id: pi_pond_analysis.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "pond analysis" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_pond_analysis_node_info() {
  return array(
	'pi_pond_analysis' => array(
      	 'name' => t('Pond Inquiry analysis'), // Required.
	 'module' => 'pi_pond_analysis',  // Required.
	 'description' => t('What is your analysis of the data you have collected in your pond inquiry?'), // Required.
	 'has_title' => TRUE,
	 'title_label' => t('Hadden Park Pond Life inquiry analysis'),
	 'has_body' => TRUE,
	 'body_label' => t('Pond analysis'),
	 'min_word_count' => 2,
	 'locked' => TRUE
	)
   );
}


/**
 * Implementation of hook_perm().
 */

function pi_pond_analysis_perm() {
  return array('create pi_pond_analysis content', 'edit pi_pond_analysis');
}

/**
 * Implementation of hook_access().
 */
function pi_pond_analysis_access($op, $node) {
  global $user;

  if ($op == 'create') {
    return TRUE;
  }

  if ($op == 'update' || $op == 'delete') {
    return TRUE;
  }
}

/**
 * Implementation of hook_form().
 */

function pi_pond_analysis_form(&$node) {

  // Get metadata for this node type
  // (we use it for labeling title and body fields).
  // We defined this in pi_pond_analysis_node_info().
  $type = node_get_types('type', $node);

  $form['title'] = array(
    '#type' => 'hidden',
    '#title' => check_plain($type->title_label),
    '#required' => FALSE,
    '#default_value' => check_plain($type->title_label),
    '#weight' => -5
  );

  $form['textarea_fieldset'] = array(
    '#type' => 'fieldset'
  );
  
  $form['textarea_fieldset']['pond_analysis'] = array(
    '#type' => 'textarea',
    '#title' => t('My analysis of the data is '),
    '#required' => TRUE,
    '#default_value' => $node->pond_analysis,
    '#resizable' => FALSE,
    '#rows' => 2,
    '#cols' => 40,
    '#weight' => 2
  );
  

  $prefix .= "<p>Based on the data you have collected, what are the key findings you have made?</p>";
  $prefix .= "<p>Write your analysis here</p>";
 
  $form['#prefix'] = $prefix;
  
  return $form;

}

/**
 * Implementation of hook_insert().
 */

 
function pi_pond_analysis_insert($node) {
  db_query("INSERT INTO {pi_pond_analysis} (nid, vid, pond_analysis) VALUES (%d, %d,'%s')",
    $node->nid, $node->vid, $node->pond_analysis);
}

/**
 * Implementation of hook_update().
 */

function pi_pond_analysis_update($node) {
  if ($node->revision) {
    pi_pond_analysis_insert($node);
  }
  
  else {
    db_query("UPDATE {pi_pond_analysis} SET pond_analysis = '%s' WHERE vid = %d", $node->pond_analysis,  $node->vid);
  }
}

/**
 * Implementation of hook_delete().
 */

function pi_pond_analysis_delete(&$node) {
  // Delete the related information we were saving for this node.
  db_query('DELETE FROM {pi_pond_analysis} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_pond_analysis_load($node) {
  return db_fetch_object(db_query('SELECT * FROM {pi_pond_analysis} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_pond_analysis_view($node, $teaser = FALSE, $page = FALSE) {
  if (!$teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);

    $node->content['pi_pond_analysis'] = array(
    '#value' => theme('pi_pond_analysis', $node),
    '#weight' => 2
    );
      
  }

  if ($teaser) {
    // Use Drupal's default node view.
    $node = node_prepare($node, $teaser);
  }

  return $node;
}

function pi_pond_analysis_theme() {
  return array(
    'pi_pond_analysis' => array(
      'arguments' => array('node'),
    ),
  );
}


function theme_pi_pond_analysis($node) {
  $output = '<div class="pi_pond_analysis">Your analysis is: ' . check_plain($node->pond_analysis). '</div><br />';
  
  return $output;
}

