<?php


function pi_register_forms_form_user_register_alter(&$form, &$form_state) {
	$form['institution'] = array(
			'#type' => 'textfield',
			'#title' => 'Institution',
			'#description' => 'Instution name',
			'#required' => FALSE,
			'#element_validate' => array('pi_register_forms_validate_trap'),
			'#prefix' => '<div class="pi_register_forms_item">',
			'#suffix' => '</div>',
	);
	
	return;
}

function pi_register_forms_validate_trap($element, &$form_state) {
	if (strlen($form_state['values']['institution']) > 0) {
		die('');
	}
}

