<?php
// $Id: pi_about_datalogger.module,v 1.1 2009/11/25 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_about_datalogger" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_about_datalogger_node_info() {

    return array(
    'pi_about_datalogger' => array(
    'name' => t('About Data Logger'), // Required.
    'module' => 'pi_about_datalogger',  // Required.
    'description' => t('About the data logger data '), // Required.
    'has_title' => TRUE,
    'title_label' => t('Looking at the data logger data'),
    'has_body' => FALSE,
    'body_label' => t('Looking at the data logger data'),
    'locked' => TRUE)
    );

}


/**
 * Implementation of hook_perm().
 */

function pi_about_datalogger_perm() {
    return array('create pi_about_datalogger content', 'edit pi_about_datalogger');
}

/**
 * Implementation of hook_access().
 */
function pi_about_datalogger_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    }
}

/**
 * Implementation of hook_form().
 */

function pi_about_datalogger_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_about_datalogger_node_info().
    $type = node_get_types('type', $node);
  	global $user;
  
  	$node_details = get_inquiry_details_from_current_path();
  	if (is_numeric($node_details->activity_id)) {
  		$current_activity = load_activity($node_details->activity_id);
  	}
  	
  	if ($current_activity->name) {
  		drupal_set_title(t($current_activity->name));
  	}

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );

    $form['height'] = array(
        '#type' => 'textarea',
        '#title' => t('Are all bird feeders at similar height?'),
        '#required' => FALSE,
        '#default_value' => $node->height,
        '#description' => t('Type in your notes about bird height'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -4
    );
    $form['coverage'] = array(
        '#type' => 'textarea',
        '#title' => t('Did all trees have the same amount of leaf coverage?'),
        '#required' => FALSE,
        '#default_value' => $node->coverage,
        '#description' => t('Type in your notes about leaf coverage'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -3
    );
    $form['tree'] = array(
        '#type' => 'textarea',
        '#title' => t('Have all trees got a tree nearby?'),
        '#required' => FALSE,
        '#default_value' => $node->tree,
        '#description' => t('Type in your notes about the trees'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -2
    );
        $form['distance'] = array(
        '#type' => 'textarea',
        '#title' => t('Are all feeders at similar distance from trunk? Does this say anything about the tree?'),
        '#required' => FALSE,
        '#default_value' => $node->distance,
        '#description' => t('Type in your notes about the feeder distances and what you think this means'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -1
    );

    $prefix = "";

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>About data logger data</p>";
    }
*/
    
    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_about_datalogger_insert($node) {
    db_query("INSERT INTO {pi_about_datalogger} (nid, vid, height, coverage, tree, distance) VALUES ('%d', '%d', '%s', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->height, $node->coverage, $node->tree, $node->distance);
} 

/* Implementation of hook_update().
 */

function pi_about_datalogger_update($node) {
    if ($node->revision) {
        pi_about_datalogger_insert($node);
    }

    else {
        db_query("UPDATE {pi_about_datalogger} SET height = '%s', coverage = '%s', tree = '%s', distance = '%s' WHERE vid = %d", $node->height, $node->coverage, $node->tree, $node->distance, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_about_datalogger_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_about_datalogger} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_about_datalogger_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_about_datalogger} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_about_datalogger_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_about_datalogger'] = array(
            '#value' => theme('pi_about_datalogger', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_about_datalogger_theme() {
    return array(
    'pi_about_datalogger' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_about_datalogger($node) {

    $output = '<p><strong>Are all bird feeders at similar height?</strong> ' . check_plain($node->height). '</p>';
    $output .= '<p><strong>Did all trees have the same amount of leaf coverage?</strong> ' . check_plain($node->coverage). '</p>';
    $output .= '<p><strong>Have all trees got a tree nearby?</strong> ' . check_plain($node->tree). '</p>';
    $output .= '<p><strong>Are all feeders at similar distance from trunk? Does this say anything about the tree?</strong> ' . check_plain($node->distance). '</p>';

    return $output;
}

