<?php
// $Id: pi_about_feeders.module,v 1.0 2009/11/21 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_about_feeders" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_about_feeders_node_info() {

    return array(
    'pi_about_feeders' => array(
    'name' => t('About feeders'), // Required.
    'module' => 'pi_about_feeders',  // Required.
    'description' => t('About feeders'), // Required.
    'has_title' => TRUE,
    'title_label' => t('About feeders'),
    'has_body' => FALSE,
    'body_label' => t('Feeders'),
    'locked' => TRUE)
    );

}


//hide node revisions box - this is a node type often set to keep revisions
//if form alter not included then user sees the log message box
function pi_about_feeders_form_alter(&$form, $form_state, $form_id) {
    global $user; // Bring $user object into scope if displaying shall depend on userid or role
    #if ( $user->uid != 1 ) // 0 -> Anonymous, 1 -> SuperAdmin, 2+ -> Authenticated users
    if ( !in_array('USER ROLE NAME', $user->roles) ) // Check for role (using role name)
    {
    // add class 'hideme' to elements which shall be hidden
        $form['revision_information']['#attributes'] = array('class' => 'hideme'); // Revision information
    // This class has been added to the CSS file:
    //  .hideme { display: none; }
    }
}

/**
 * Implementation of hook_perm().
 */

function pi_about_feeders_perm() {
    return array('create pi_about_feeders content', 'edit pi_about_feeders');
}

/**
 * Implementation of hook_access().
 */
function pi_about_feeders_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_about_feeders'));
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    //return (user_access('edit own pi_about_feeders'));
    }
}

/**
 * Implementation of hook_form().
 */

function pi_about_feeders_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_about_feeders_node_info().
    $type = node_get_types('type', $node);
    global $user;

    $node_details = get_inquiry_details_from_current_path();
    if (is_numeric($node_details->activity_id)) {
        $current_activity = load_activity($node_details->activity_id);
    }

    if ($current_activity->name) {
        drupal_set_title(t($current_activity->name));
    }

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -7
    );

    $form['hide'] = array(
        '#type' => 'fieldset',
        '#title' => t('Attenborough hide'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
    );

    $form['hide']['h_see'] = array(
        '#type' => 'textarea',
        '#title' => t('What birds did you see?'),
        '#required' => FALSE,
        '#default_value' => $node->h_see,
        '#resizable' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -6
    );
    $form['hide']['h_many'] = array(
        '#type' => 'textfield',
        '#title' => t('How many birds visited the feeder?'),
        '#required' => FALSE,
        '#default_value' => $node->h_many,
        '#weight' => -5
    );
    $form['hide']['h_common'] = array(
        '#type' => 'textfield',
        '#title' => t('What was the most common bird?'),
        '#required' => FALSE,
        '#default_value' => $node->h_common,
        '#weight' => -4
    );
    $form['hide']['h_visits'] = array(
        '#type' => 'textfield',
        '#title' => t('How many visits did it do?'),
        '#required' => FALSE,
        '#default_value' => $node->h_visits,
        '#weight' => -3
    );
    $form['hide']['h_time'] = array(
        '#type' => 'select',
        '#title' => t('Did all the birds spend the same time at the feeder?'),
        '#required' => FALSE,
        '#default_value' => $node->h_time,
        '#options' => array("yes" => "yes", "no" => "no"),
        '#weight' => -2
    );
    $form['hide']['h_comments'] = array(
        '#type' => 'textarea',
        '#title' => t('Comments'),
        '#required' => FALSE,
        '#default_value' => $node->h_comments,
        '#resizable' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -1
    );

    $form['garden'] = array(
        '#type' => 'fieldset',
        '#title' => t('Attenborough garden'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
    );

    $form['garden']['g_see'] = array(
        '#type' => 'textarea',
        '#title' => t('What birds did you see?'),
        '#required' => FALSE,
        '#default_value' => $node->g_see,
        '#resizable' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -6
    );
    $form['garden']['g_many'] = array(
        '#type' => 'textfield',
        '#title' => t('How many birds visited the feeder?'),
        '#required' => FALSE,
        '#default_value' => $node->g_many,
        '#weight' => -5
    );
    $form['garden']['g_common'] = array(
        '#type' => 'textfield',
        '#title' => t('What was the most common bird?'),
        '#required' => FALSE,
        '#default_value' => $node->g_common,
        '#weight' => -4
    );
    $form['garden']['g_visits'] = array(
        '#type' => 'textfield',
        '#title' => t('How many visits did it do?'),
        '#required' => FALSE,
        '#default_value' => $node->g_visits,
        '#weight' => -3
    );
    $form['garden']['g_time'] = array(
        '#type' => 'select',
        '#title' => t('Did all the birds spend the same time at the feeder?'),
        '#required' => FALSE,
        '#default_value' => $node->g_time,
        '#options' => array("yes" => "yes", "no" => "no"),
        '#weight' => -2
    );
    $form['garden']['g_comments'] = array(
        '#type' => 'textarea',
        '#title' => t('Comments'),
        '#required' => FALSE,
        '#default_value' => $node->g_comments,
        '#resizable' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -1
    );

    $prefix = "";

    if(arg(2) == 'edit') {
        $link = build_link('node', $node->nid, 'view', $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

        switch ($current_activity->destination) {
            case "self":
                $destination = "";
                break;
            case "phase":
                $destination = t("destination=" . build_link("phase", $node_details->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id,$node_details->activity_id));
                break;
            default:
                $destination = t("destination=" . build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id));
                break;
        }

        $prefix .= '<div style=\'display: block; clear: both; float: right;\'>';
        $prefix .= l(t('View'), $link,  array('html' => true, 'query' => $destination));
        $prefix .= '</div>';
    }

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>About habitats.</p>";
    }
*/

    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_about_feeders_insert($node) {
    db_query("INSERT INTO {pi_about_feeders} (nid, vid, h_see, h_many, h_common, h_visits, h_time, h_comments, g_see, g_many, g_common, g_visits, g_time, g_comments) VALUES ('%d', '%d', '%s', '%d', '%s', '%d', '%s', '%s', '%s', '%d', '%s', '%d', '%s', '%s')",
        $node->nid, $node->vid, $node->h_see, $node->h_many, $node->h_common, $node->h_visits, $node->h_time, $node->h_comments, $node->g_see, $node->g_many, $node->g_common, $node->g_visits, $node->g_time, $node->g_comments);
}

/**
 * Implementation of hook_update().
 */

function pi_about_feeders_update($node) {
    if ($node->revision) {
        pi_about_feeders_insert($node);
    }

    else {
        db_query("UPDATE {pi_about_feeders} SET h_see = '%s', h_many = '%d', h_common = '%s', h_visits = '%d', h_time = '%s', h_comments = '%s', g_see = '%s', g_many = '%d', g_common = '%s', g_visits = '%d', g_time = '%s', g_comments = '%s' WHERE vid = %d", $node->h_see, $node->h_many, $node->h_common, $node->h_visits, $node->h_time, $node->h_comments, $node->g_see, $node->g_many, $node->g_common, $node->g_visits, $node->g_time, $node->g_comments, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_about_feeders_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_about_feeders} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_about_feeders_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_about_feeders} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_about_feeders_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_about_feeders'] = array(
            '#value' => theme('pi_about_feeders', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_about_feeders_theme() {
    return array(
    'pi_about_feeders' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_about_feeders($node) {

    $output = '';

    global $user;
    $node_details = get_inquiry_details_from_current_path();

    if(check_node_function_of_activity ($node_details->inquiry_id, $node_details->activity_id, $user->uid, 'edit')) {

        $link = build_link('node', $node->nid, 'edit', $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

        switch ($current_activity->destination) {
            case "self":
                $destination = "";
                break;
            case "phase":
                $destination = t("destination=" . build_link("phase", $node_details->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id,$node_details->activity_id));
                break;
            default:
                $destination = t("destination=" . build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id));
                break;
        }

        $output .= '<div style=\'display: block; clear: both; float: right;\'>';
        $output .= l(t('Edit'), $link,  array('html' => true, 'query' => $destination));
        $output .= '</div>';

    }

    $output .= '<div style=\'display: block; clear: both;\'>';

    $output .= "<div style = 'display: block; float: left; width: 200px; margin: 0 1em 0 0; padding: 0 1em 0 1em; border: solid 1px black;'>";
    $output .= '<h2>Attenborough hide</h2>';
    $output .= '<p><strong>What birds did you see?</strong> ' . check_plain($node->h_see). '</p>';
    $output .= '<p><strong>How many birds visited the feeder?</strong> ' . check_plain($node->h_many). '</p>';
    $output .= '<p><strong>What was the most common bird?</strong> ' . check_plain($node->h_common). '</p>';
    $output .= '<p><strong>How many visits did it do?</strong> ' . check_plain($node->h_visits). '</p>';
    $output .= '<p><strong>Did all birds spend the same time at the feeder?</strong> ' . check_plain($node->h_time). '</p>';
    $output .= '<p><strong>Comments?</strong> ' . check_plain($node->h_comments). '</p>';
    $output .= '</div>';

    $output .= "<div style = 'display: block; float: left; width: 200px; margin: 0; padding: 0 1em 0 1em; border: solid 1px black;'>";
    $output .= '<h2>Attenborough garden</h2>';
    $output .= '<p><strong>What birds did you see?</strong> ' . check_plain($node->g_see). '</p>';
    $output .= '<p><strong>How many birds visited the feeder?</strong> ' . check_plain($node->g_many). '</p>';
    $output .= '<p><strong>What was the most common bird?</strong> ' . check_plain($node->g_common). '</p>';
    $output .= '<p><strong>How many visits did it do?</strong> ' . check_plain($node->g_visits). '</p>';
    $output .= '<p><strong>Did all birds spend the same time at the feeder?</strong> ' . check_plain($node->g_time). '</p>';
    $output .= '<p><strong>Comments?</strong> ' . check_plain($node->g_comments). '</p>';
    $output .= '</div>';

    $output .= '</div>';

    return $output;
}

