<?php

// $Id: pi_inquiry_info.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $



function pi_inquiry_info_block($op = 'list', $delta = 0, $edit = array()) {

	switch ($op) {
		case 'list':
			$blocks[0]['info'] = t('New Activity summary');
			return $blocks;

		case 'view':
			global $user;
			$node_details = get_inquiry_details_from_current_path();

			if ($node_details->inquiry_id) {
				$loaded_inquiry = node_load($node_details->inquiry_id);
				$block['subject'] = l(check_plain($loaded_inquiry->title), "inquiry/" . $node_details->inquiry_id);
				$block['content'] = t($loaded_inquiry->body);
			}
			return $block;
	}
}

