<?php
// $Id: pi_habitats.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_habitats" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_habitats_node_info() {

    return array(
    'pi_habitats' => array(
    'name' => t('About habitats'), // Required.
    'module' => 'pi_habitats',  // Required.
    'description' => t('About habitats'), // Required.
    'has_title' => TRUE,
    'title_label' => t('About habitats'),
    'has_body' => FALSE,
    'body_label' => t('Habitats'),
    'locked' => TRUE)
    );

}


//hide node revisions box - this is a node type often set to keep revisions
//if form alter not included then user sees the log message box
function pi_habitats_form_alter(&$form, $form_state, $form_id)
{
  global $user; // Bring $user object into scope if displaying shall depend on userid or role
  #if ( $user->uid != 1 ) // 0 -> Anonymous, 1 -> SuperAdmin, 2+ -> Authenticated users
  if ( !in_array('USER ROLE NAME', $user->roles) ) // Check for role (using role name)
  {
    // add class 'hideme' to elements which shall be hidden
    $form['revision_information']['#attributes'] = array('class' => 'hideme'); // Revision information
    // This class has been added to the CSS file:
   //  .hideme { display: none; }
  }
}

/**
 * Implementation of hook_perm().
 */

function pi_habitats_perm() {
    return array('create pi_habitats content', 'edit pi_habitats');
}

/**
 * Implementation of hook_access().
 */
function pi_habitats_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_habitats'));
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    //return (user_access('edit own pi_habitats'));
    }
}

/**
 * Implementation of hook_form().
 */

function pi_habitats_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_habitats_node_info().
    $type = node_get_types('type', $node);
  	global $user;
  
  	$node_details = get_inquiry_details_from_current_path();
  	if (is_numeric($node_details->activity_id)) {
  		$current_activity = load_activity($node_details->activity_id);
  	}
  	
  	if ($current_activity->name) {
  		drupal_set_title(t($current_activity->name));
  	}

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -5
    );

    $form['what'] = array(
        '#type' => 'textarea',
        '#title' => t('What is a habitat?'),
        '#required' => FALSE,
        '#default_value' => $node->what,
        '#description' => t('Type in what you think a habitat is'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -4
    );
    $form['features'] = array(
        '#type' => 'textarea',
        '#title' => t('What features would you expect in a habitat?'),
        '#required' => FALSE,
        '#default_value' => $node->features,
        '#description' => t('Type the features that you would expect a habitat to have'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -3
    );
    $form['compare'] = array(
        '#type' => 'textarea',
        '#title' => t('How does a man made habitat compare with a natural habitat?'),
        '#required' => FALSE,
        '#default_value' => $node->compare,
        '#description' => t('Explain how you think man made habitats compare with natural habitats'),
        '#resizable' => FALSE,
        '#rows' => 5,
        '#cols' => 40,
        '#weight' => -2
    );

    $prefix = "";

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>About habitats.</p>";
    }
*/
    
    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_habitats_insert($node) {
    db_query("INSERT INTO {pi_habitats} (nid, vid, what, features, compare) VALUES ('%d', '%d', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->what, $node->features, $node->compare);
}

/**
 * Implementation of hook_update().
 */

function pi_habitats_update($node) {
    if ($node->revision) {
        pi_habitats_insert($node);
    }

    else {
        db_query("UPDATE {pi_habitats} SET what = '%s', features = '%s', compare = '%s'  WHERE vid = %d", $node->what, $node->features, $node->compare, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_habitats_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_habitats} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_habitats_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_habitats} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_habitats_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_habitats'] = array(
            '#value' => theme('pi_habitats', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_habitats_theme() {
    return array(
    'pi_habitats' => array(
    'arguments' => array('node'),
    ),
    );
}


function theme_pi_habitats($node) {

    $output = '<p><strong>What is a habitat?</strong> ' . check_plain($node->what). '</p>';
    $output .= '<p><strong>What features would you expect in a habitat?</strong> ' . check_plain($node->features). '</p>';
    $output .= '<p><strong>How does a man made habitat compare with a natural habitat?</strong> ' . check_plain($node->compare). '</p>';

    return $output;
}

