<?php

/**
 * Implementation of hook_install(): registers the supported activities with 
 * the authoring tool.
 */
function inquiry_basic_activities_designer_install() {
  inquiry_available_features_register('activity', 'pi_read_information', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_wiki_notes', 'inquiry_basic_activities_designer');

  inquiry_available_features_register('activity', 'pi_hypothesis', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_hypothesis_conclusion', 'inquiry_basic_activities_designer');

  inquiry_available_features_register('activity', 'pi_sort_key_questions', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_sort_key_answers', 'inquiry_basic_activities_designer');

  inquiry_available_features_register('activity', 'pi_methodology', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_sort_data', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_explore_tool', 'inquiry_basic_activities_designer');

  inquiry_available_features_register('activity', 'pi_sort_result_presentations', 'inquiry_basic_activities_designer');
  inquiry_available_features_register('activity', 'pi_data_spreadsheet', 'inquiry_basic_activities_designer');
}

/**
 * Implementation of hook_uninstall(): removes the registered activities.
 */
function inquiry_basic_activities_designer_uninstall() {
  inquiry_available_features_forget('activity', 'pi_read_information');
  inquiry_available_features_forget('activity', 'pi_wiki_notes');

  inquiry_available_features_forget('activity', 'pi_hypothesis');
  inquiry_available_features_forget('activity', 'pi_hypothesis_conclusion');

  inquiry_available_features_forget('activity', 'pi_sort_key_questions');
  inquiry_available_features_forget('activity', 'pi_sort_key_answers');

  inquiry_available_features_forget('activity', 'pi_methodology');
  inquiry_available_features_forget('activity', 'pi_sort_data');
  inquiry_available_features_forget('activity', 'pi_explore_tool');

  inquiry_available_features_forget('activity', 'pi_sort_result_presentations');
  inquiry_available_features_forget('activity', 'pi_data_spreadsheet');
}

