<?php
// $Id: pi_fairtest_weight.module,v 1.0 2009/11/27 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_fairtest_weight" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_fairtest_weight_node_info() {

    return array(
    'pi_fairtest_weight' => array(
    'name' => t('Analysis of fair test weight data'), // Required.
    'module' => 'pi_fairtest_weight',  // Required.
    'description' => t('Analysis of fair test weight data'), // Required.
    'has_title' => TRUE,
    'title_label' => t('Analysis of fair test weight data'),
    'has_body' => FALSE,
    'body_label' => t('Analysis of fair test weight data'),
    'locked' => TRUE)
    );

}


//hide node revisions box - this is a node type often set to keep revisions
//if form alter not included then user sees the log message box
function pi_fairtest_weight_form_alter(&$form, $form_state, $form_id) {
    global $user; // Bring $user object into scope if displaying shall depend on userid or role
    #if ( $user->uid != 1 ) // 0 -> Anonymous, 1 -> SuperAdmin, 2+ -> Authenticated users
    if ( !in_array('USER ROLE NAME', $user->roles) ) // Check for role (using role name)
    {
    // add class 'hideme' to elements which shall be hidden
        $form['revision_information']['#attributes'] = array('class' => 'hideme'); // Revision information
    // This class has been added to the CSS file:
    //  .hideme { display: none; }
    }
}

/**
 * Implementation of hook_perm().
 */

function pi_fairtest_weight_perm() {
    return array('create pi_fairtest_weight content', 'edit pi_fairtest_weight');
}

/**
 * Implementation of hook_access().
 */
function pi_fairtest_weight_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_fairtest_weight'));
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    //return (user_access('edit own pi_fairtest_weight'));
    }
}

/**
 * Implementation of hook_form().
 */

function pi_fairtest_weight_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_fairtest_weight_node_info().
    $type = node_get_types('type', $node);
    global $user;

    $node_details = get_inquiry_details_from_current_path();
    if (is_numeric($node_details->activity_id)) {
        $current_activity = load_activity($node_details->activity_id);
    }

    if ($current_activity->name) {
        drupal_set_title(t($current_activity->name));
    }

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -6
    );

    $form['noise'] = array(
        '#type' => 'textarea',
        '#title' => t('What did you notice in the feeder that was exposed to noise?'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
	'#rows' => 3,
        '#cols' => 40,
        '#weight' => -5
    );

    $form['quiet'] = array(
        '#type' => 'textarea',
        '#title' => t('What did you notice in the feeder that was in the quiet place?'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -4
    );
    $form['changes'] = array(
        '#type' => 'textarea',
        '#title' => t('What do you think caused the changes you observed?'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -3
    );
        $form['evidence'] = array(
        '#type' => 'textarea',
        '#title' => t('What is your evidence for this?'),
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
        '#rows' => 3,
        '#cols' => 40,
        '#weight' => -2
    );


    $prefix = "";

    if(arg(2) == 'edit') {
        $link = build_link('node', $node->nid, 'view', $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

        switch ($current_activity->destination) {
            case "self":
                $destination = "";
                break;
            case "phase":
                $destination = t("destination=" . build_link("phase", $node_details->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id,$node_details->activity_id));
                break;
            default:
                $destination = t("destination=" . build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id));
                break;
        }

        $prefix .= '<p>';
        $prefix .= l(t('View'), $link,  array('html' => true, 'query' => $destination));
        $prefix .= '</p>';
    }

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>Analysing the fair test weight data</p>";
    }
*/

    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_fairtest_weight_insert($node) {
    db_query("INSERT INTO {pi_fairtest_weight} (nid, vid, noise, quiet, changes, evidence) VALUES ('%d', '%d', '%s', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->noise, $node->quiet, $node->changes, $node->evidence);
}

/**
 * Implementation of hook_update().
 */

function pi_fairtest_weight_update($node) {
    if ($node->revision) {
        pi_fairtest_weight_insert($node);
    }

    else {
        db_query("UPDATE {pi_fairtest_weight} SET noise = '%s', quiet = '%s', changes = '%s', evidence = '%s' WHERE vid = %d", $node->noise, $node->quiet, $node->changes, $node->evidence, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_fairtest_weight_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_fairtest_weight} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_fairtest_weight_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_fairtest_weight} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_fairtest_weight_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_fairtest_weight'] = array(
            '#value' => theme('pi_fairtest_weight', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_fairtest_weight_theme() {
    return array(
    'pi_fairtest_weight' => array(
    'arguments' => array('node'),
    ),
    );
}

function theme_pi_fairtest_weight($node) {

    $output = '<p><strong>What did you notice in the feeder that was exposed to noise?</strong> ' . check_plain($node->noise). '</p>';
    $output .= '<p><strong>What did you observe in the feeder that was in the quiet place?</strong> ' . check_plain($node->quiet). '</p>';
    $output .= '<p><strong>What do you think caused the changes you observed?</strong> ' . check_plain($node->changes). '</p>';
    $output .= '<p><strong>What is your evidence for this?</strong> ' . check_plain($node->evidence). '</p>';

    return $output;
}
