<?php
// $Id: teacher_tools.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $

/**
 * @file
 * Implements teacher tools.
 */


/**
 * MISSING
 *
 * @return unkown
 */
function pi_teacher_tools_menu() {

	$items = array();

	// Do not cache this menu item during the development of this module.

  $items['dashboard'] = array(
    'title' => t('Phase'),
    'page callback' => 'pi_dashboard',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
	);

	$items['events'] = array(
    'title' => t('Phase'),
    'page callback' => 'pi_events',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
	);

	return $items;
}

/**
 * MISSING
 *
 * @return string
 */
function pi_dashboard() {
	drupal_set_title('');

	$content = "<h1>Dashboard</h1>";

	global $user;
	$details = get_inquiry_details_from_current_path();

	$stages = pi_stage_load_nids_for_user($details->inquiry_id, $user->uid);

	$current_stage = get_current_stage_of_inquiry_and_user ($details->inquiry_id, $user->uid);
	$current_stage_id = $current_stage->stage_id;

	if ($details->stage_id) {
		$selected_stage = $details->stage_id;
	}
	else {
		$selected_stage = $current_stage_id;
	}

	$content .= "<div>";
	foreach($stages as $stage_nid)
	{
		$stage = node_load($stage_nid);
		$content .= "<div style=\"float: left; width: 8em\">";
		if ($stage->nid == $selected_stage)
		{
			$content .= "<b>" . $stage->title . "</b>";
		}
		else
		{
			$content .= l(t($stage->title), build_teacher_tool_link("dashboard", $details->inquiry_id, $stage->nid), array());
			//$content .= $stage->name . " ";
		}
		$content .= "</div>";
	}
	$content .= "</div>";

	$activities = get_activities_of_stage_phase_and_user ($details->inquiry_id, $selected_stage, NULL, $user->uid);
	
	
	
	$content .= "<br/><table class=\"home-table\"><tr>";
	foreach ($activities as $activity)
	{
		$loaded_activity = load_activity($activity->activity_id);
		$loaded_activity_actor = load_activity_actor($details->inquiry_id, $activity->activity_id);
		$content .= "<td><b>" . $loaded_activity->name . "</b></td>";
	}

	$content .= "</tr><tr>";

	foreach ($activities as $activity) {

		//get_activity_participants($node_details)
		$content .= "<td valign=\"top\">";
		$ob = new stdClass();
		$ob->inquiry_id = $details->inquiry_id;
		$ob->activity_id = $activity->activity_id;
		$ob->stage_id = $selected_stage;

		$ap_result = get_activity_participants($ob);
		$audience = $ap_result["audience"];
		$activity_participants = $ap_result["activity_participants"];
			
		/*get the status for each actual audience*/
		//use activity status
			
		$content .= generate_status_table($activity_participants, $ob, $audience);

		get_activity_participants($ob);
		$contnet .= "</td>";
	}

	$content .= "</tr></table>";
	return $content;

}

/**
 * MISSING
 *
 * @return string
 */
function pi_events() {
	drupal_set_title('');

	return "<h1>Events</h1><p>This will allow the teacher to identify events and take actions. For example detecting that student X did not complete Activity 1 in the previous stage and decide to fill it in with stock data.";
}


