<?php
// $Id$

/**
 * @file
 * Implements various blocks for Activity Guide navigation.
 */

 /**  and n.uid = %d' $uid,
 * Implementation of hook_block().
 */
function pi_information_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
    
      $blocks[0]['info'] = t('Measures block');
      $blocks[1]['info'] = t('Locations block');
      return $blocks;

    case 'view':
  	  
      $output = "";
              
      if (arg(0) == 'node') {
        if (is_numeric(arg(1))) {
          $node = node_load(arg(1));
          $node_type = $node->type;
        }
        elseif (arg(1) == 'add') {
          $node_type = arg(2);
        }
      };
        
      if (($delta == 0) AND (($node_type == 'pi_hypothesis') OR ($node_type == 'pi_selected_measures') OR ($node_type == 'pi_selected_measures2'))) {
        
        $counter_start = 1;
        $content_type = "pi_available_measures";
        $content_label = "measurements";
        
        $counter = $counter_start;
            
        $available_content_titles = db_query("SELECT title FROM {node} WHERE type = '%s' AND status = '1'", $content_type);
        
        $output .= "<div class='clear_both'>";
        $output .= "<div class=\"tabs\"><ul class=\"tabs primary clear-block\">";
        while ($item = db_fetch_object($available_content_titles)) {
          $output .= "<li class=\"inactive\" id='tab" . $counter . "'>";
          $output .= "<a href='#' onclick=\"show('item" . $counter . "'); setActiveTab('tab" . $counter . "'); \"><span class=\"tab\">" . $item->title . "</span></a></li>";
          $counter = $counter + 1;
        };
        $output .= "</ul>";
        $output .= "</div>";
        
        $available_content = db_query("SELECT nid, title FROM {node} WHERE type = '%s' AND status = '1'", $content_type);
        
        $counter = $counter_start;
        
        while ($item = db_fetch_object($available_content)) {
          
          $output .= "<div style = 'display: none;' id='item" . $counter . "'>";
          $node = node_load($item->nid);
          $output .= node_view($node);
          $output .= "</div>";
          $counter = $counter + 1;
            
        }
                
        $output .= "</div>";
        
        //display in the block
      	
      	$block['subject'] = t('Available ' . $content_label);
      	$block['content'] = t($output);
        
      }
      elseif (($delta == 1) AND (($node_type == 'pi_hypothesis') OR ($node_type == 'pi_selected_locations') OR ($node_type == 'pi_selected_locations2'))) {
        if (($delta == 1) AND ($node_type == 'pi_hypothesis')) {
          $tab_counter = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {node} WHERE type = 'pi_available_measures' AND status = '1'"));
          $counter_start = $tab_counter->count + 1;        
        }
        else {
          $counter_start = 1;
        };
        $content_type = "pi_available_locations";
        $content_label = "locations";
          
        $counter = $counter_start;
            
        $available_content_titles = db_query("SELECT title FROM {node} WHERE type = '%s' AND status = '1'", $content_type);
        
        $output .= "<div class='clear_both'>";
        $output .= "<div class=\"tabs\"><ul class=\"tabs primary clear-block\">";
        while ($item = db_fetch_object($available_content_titles)) {
          $output .= "<li class=\"inactive\" id='tab" . $counter . "'>";
          $output .= "<a href='#' onclick=\"show('item" . $counter . "'); setActiveTab('tab" . $counter . "'); \"><span class=\"tab\">" . $item->title . "</span></a></li>";
          $counter = $counter + 1;
        };
        $output .= "</ul>";
        $output .= "</div>";
        
        $available_content = db_query("SELECT nid, title FROM {node} WHERE type = '%s' AND status = '1'", $content_type);
        
        $counter = $counter_start;
        
        while ($item = db_fetch_object($available_content)) {
          
          $output .= "<div style = 'display: none;' id='item" . $counter . "'>";
          $node = node_load($item->nid);
          $output .= node_view($node);
          $output .= "</div>";
          $counter = $counter + 1;
            
        }
        
        $output .= "</div>";
        
        $output .= "<div class='clear_both'>";
        $output .= "<img src='files/oakgrove-map.png' />";
        $output .= "</div>";
        
        //display in the block
      	
      	$block['subject'] = t('Available ' . $content_label);
      	$block['content'] = t($output);
                    
      };
                  
      drupal_add_js(drupal_get_path('module', 'pi_information') .'/pi_information.js');
    	return $block;
      
  };
}

