<?php

// $Id: pi_header.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $

define('NQUIRE_VERSION', 'BETA3 2013-05-02');

function pi_header_block($op = 'list', $delta = 0, $edit = array()) {
	global $user;
	switch ($op) {
		case 'list':
			$blocks = array();
			$blocks[0]['info'] = t('Activity guide header');
			return $blocks;

		case 'view':
			$path = drupal_get_path('module', 'pi_header');
			$image_path = $path . '/images';
			drupal_add_css($path . '/pi_header.css');

			$details = get_inquiry_details_from_current_path();
			$inquiry = node_load($details->inquiry_id);

			//$block['subject'] = "nQuire";
			if (arg(0) == 'inquiry' || arg(0) == 'phase' || arg(0) == 'activity') {
				$image_url = url($image_path . '/octagon.png');
				$url = 'inquiry/' . $details->inquiry_id;
				$home_icon = l('<img src="' . $image_url . '" height="50px" >', $url, array('html' => TRUE));
			} else {
				$image_url = base_path() . $image_path . '/logo.png';
				$url = 'http://www.nquire.org.uk';
				$home_icon = l('<img src="' . $image_url . '" height="50px" >', $url, array('html' => TRUE));
			}

			$output = '';

			$output .= "<div class='nquire_home'>" . $home_icon . "</div>";

			$output .= "<div class='nquire'>";
			if ($inquiry != null) {
				if (isset($inquiry->title)) {
					$output .= "<div style='float: left;'><h1 class='nquire'>" . check_plain($inquiry->title) . '</h1></div>';
				}
			}
			if (arg(0) == 'inquiry' || arg(0) == 'phase' || arg(0) == 'activity' || arg(0) == 'set_stage') {
				$output .= "<div style='clear: both;'>" . pi_stage_bar() . '</div>';
			}
			$output .= "</div>";

			if (NQUIRE_VERSION) {
				$output .= "<div style='float:right;clear:right;'>" . t('Version ID') . ':&nbsp;' . NQUIRE_VERSION . "</div>";
			}

			if ($user->uid) {
				$output .= "<div style='float:right;clear:right;'>";
				$output .= "<div class='logout'>" . check_plain($user->name) . "</div>";
				$link_att = array('attributes' => array('class' => 'logout'));
				$output .= "<div style='clear:both; float:right;'>" . l(t('logout'), "logout", $link_att) . "</div>";
				$output .= "</div>";
			}

			$block['content'] = $output;
			return $block;
	}
}

function pi_stage_bar() {
	$access_data = pi_inquiry_groupings_get_access_data();

	$stage = $access_data->get_current_stage();

	$output = '<p><strong>' . t('Current stage: ') . '</strong>' . check_plain($stage->title) . '</p>';
	return $output;
}

