<?php
// $Id$: pi_data_reading.module ou_mbg Exp $

/**
 * @file
 * Functions for reading own and group data
 */
 
 function pi_show_class_data ($user) {
	$choice_group = find_class_group_gid($user);
	//$data_group = find_student_group_gid($user);
	$data_groups = student_group_list_for_class_member($user);

	$class_id = find_class_group_gid($user);
	$selected_locations_activity = 11;
	$selected_measures_activity = 10;
	$data_node_type = "pi_data";
	
	//get the selected locations
	$location_res=db_fetch_object(db_query("SELECT pi_selected_locations.selected_locations FROM pi_activity_node, node_access, pi_selected_locations WHERE pi_activity_node.activity_id=\"%d\" AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_selected_locations.nid ORDER BY pi_selected_locations.vid DESC", $selected_locations_activity, $choice_group));
	$selected_locations_array = explode(",", $location_res->selected_locations);
	$location_titleids = array();
	$lcount = 0;
	foreach ($selected_locations_array as $activity_location) {
		$location_titleids[$lcount] = array(id => $activity_location, title => db_result(db_query("SELECT title FROM node WHERE nid = %d", $activity_location)));
		$lcount++;
	}

	//get the selected measures
	$measure_res=db_fetch_object(db_query("SELECT pi_selected_measures.selected_measures FROM pi_activity_node, node_access, pi_selected_measures WHERE pi_activity_node.activity_id=\"%d\" AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_selected_measures.nid ORDER BY pi_selected_measures.vid DESC", $selected_measures_activity, $choice_group));
	$measures = explode(",", $measure_res->selected_measures);
	$measure_titles = array();
	$mcount = 0;
	foreach ($measures as $measure) {
		$measure_titles[$mcount][title] = db_result(db_query("SELECT title FROM node WHERE nid = %d", $measure));
		$measure_titles[$mcount][type] = db_result(db_query("SELECT data_type FROM pi_available_measures WHERE nid = %d", $measure));
		$measure_titles[$mcount][options] = explode("\n", db_result(db_query("SELECT options FROM pi_available_measures WHERE nid = %d", $measure)));
		$mcount++;
	}
	
	if ($mcount > 0 && $lcount > 0) {
	//get data for each location
	print t("<p><strong>Tip:</strong> You can copy and paste this table into Word or Excel.</p>");
	print t ("<table>");
	print t("<tr>");
	print t("<th>Location</th>");
	foreach ($measure_titles as $measure_title) {
		if ($measure_title[type] == 0) {
			print t("<th>" . $measure_title[title] . "</th>");
		}
	}
	print t("</tr>");
  $count = 1;
	foreach ($location_titleids as $location_titleid) {
		$group_count = 0;
		foreach ($data_groups as $data_group) {
			$data_ress[$group_count] = db_fetch_object(db_query("SELECT pi_data.* FROM pi_activity, pi_activity_node, node_access, pi_data WHERE pi_activity.name = \"%s\" AND pi_activity.activity_id = pi_activity_node.activity_id AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_data.nid ORDER BY pi_data.vid DESC", $location_titleid[title], $data_group));
			$group_count++;
		}
		
//		$data_res = db_fetch_object(db_query("SELECT pi_data.* FROM pi_activity, pi_activity_node, node_access, pi_data WHERE pi_activity.name = \"%s\" AND pi_activity.activity_id = pi_activity_node.activity_id AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_data.nid ORDER BY pi_data.vid DESC", $location_titleid[title], $data_group));
		
    if (($count % 2) == 0) {
		  print t("<tr class=\"even\">");
    }
    else {
      print t("<tr class=\"odd\">");
    };
		print t("<td>" . $location_titleid[title] . "</td>");
		$float_count = 1;
		$text_count = 1;
		$menu_count = 1;
		foreach ($measure_titles as $measure_title) {
			if ($measure_title[type] == 0) {
				$obj = t("float_value_" . $float_count);
				print t("<td>" );
				$cell_count = 0;
				$cell_total = 0;
				foreach ($data_ress as $data_res) {
					if ($data_res -> $obj) {
						$cell_count++;
						$cell_total  = $cell_total + $data_res -> $obj;
					}
				}
				if ($cell_count > 0) {
					$cell_average = $cell_total / $cell_count;
					print t(round($cell_average, 1) . "</td>");
				}
				$float_count++;
			}
		}
		print t("</tr>");
		$count++;
	}
	print t ("</table>");
	}
}
 
 function  pi_show_group_data ($user) {
	
	$middle = db_result(db_query("SELECT nid FROM og_uid WHERE nid = 184 AND uid = %d", $user->uid));
	$top = db_result(db_query("SELECT nid FROM og_uid WHERE nid = 183 AND uid = %d", $user->uid));
	if ($top) {
		$group_id = find_student_group_gid($user);
		show_data_for_choice_and_data_groups($group_id, $group_id, 3, 2);
	}
	else {
		if ($middle) {
			$group_id = find_student_group_gid($user);
			$class_id = find_class_group_gid($user);
			show_data_for_choice_and_data_groups($class_id, $group_id, 11, 10);
		}
	}
}
	
function show_data_for_choice_and_data_groups ($choice_group, $data_group, $selected_locations_activity, $selected_measures_activity) {
	$data_node_type = "pi_data";
	
	//get the selected locations
	$location_res=db_fetch_object(db_query("SELECT pi_selected_locations.selected_locations FROM pi_activity_node, node_access, pi_selected_locations WHERE pi_activity_node.activity_id=\"%d\" AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_selected_locations.nid ORDER BY pi_selected_locations.vid DESC", $selected_locations_activity, $choice_group));
	$selected_locations_array = explode(",", $location_res->selected_locations);
	$location_titleids = array();
	$lcount = 0;
	foreach ($selected_locations_array as $activity_location) {
		$location_titleids[$lcount] = array(id => $activity_location, title => db_result(db_query("SELECT title FROM node WHERE nid = %d", $activity_location)));
		$lcount++;
	}

	//get the selected measures
	$measure_res=db_fetch_object(db_query("SELECT pi_selected_measures.selected_measures FROM pi_activity_node, node_access, pi_selected_measures WHERE pi_activity_node.activity_id=\"%d\" AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_selected_measures.nid ORDER BY pi_selected_measures.vid DESC", $selected_measures_activity, $choice_group));
	$measures = explode(",", $measure_res->selected_measures);
	$measure_titles = array();
	$mcount = 0;
	foreach ($measures as $measure) {
		$measure_titles[$mcount][title] = db_result(db_query("SELECT title FROM node WHERE nid = %d", $measure));
		$measure_titles[$mcount][type] = db_result(db_query("SELECT data_type FROM pi_available_measures WHERE nid = %d", $measure));
		$measure_titles[$mcount][options] = explode("\n", db_result(db_query("SELECT options FROM pi_available_measures WHERE nid = %d", $measure)));
		$mcount++;
	}
	
	if ($mcount > 0 && $lcount > 0) {
	print t("<p><strong>Tip:</strong> You can copy and paste this table into Word or Excel.</p>");
	//get data for each location
	print t ("<table>");
	print t("<tr>");
	print t("<th>Location</th>");
	foreach ($measure_titles as $measure_title) {
		print t("<th>" . $measure_title[title] . "</th>");
	}
	print t("</tr>");
	$count = 1;
	foreach ($location_titleids as $location_titleid) {
		$data_res = db_fetch_object(db_query("SELECT pi_data.* FROM pi_activity, pi_activity_node, node_access, pi_data WHERE pi_activity.name = \"%s\" AND pi_activity.activity_id = pi_activity_node.activity_id AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_data.nid ORDER BY pi_data.vid DESC", $location_titleid[title], $data_group));
//		$data_res = db_fetch_object(db_query("SELECT pi_data.* FROM pi_activity, pi_activity_node, node_access, pi_data WHERE pi_activity.name = \"%s\" AND pi_activity.activity_id = pi_activity_node.activity_id AND pi_activity_node.nid = node_access.nid AND node_access.gid = %d AND node_access.nid = pi_data.nid ORDER BY pi_data.vid DESC", $location_titleid[title], $data_group));
		if (($count % 2) == 0) {
		  print t("<tr class=\"even\">");
    }
    else {
      print t("<tr class=\"odd\">");
    };
		print t("<td>" . $location_titleid[title] . "</td>");
		$float_count = 1;
		$text_count = 1;
		$menu_count = 1;
		foreach ($measure_titles as $measure_title) {
			switch ($measure_title[type]) {
			case 0:
				$obj = t("float_value_" . $float_count);
				print t("<td>" . $data_res -> $obj . "</td>");
				$float_count++;
				break;
			case 1:
				$obj = t("text_value_" . $text_count);
				print t("<td> " . $data_res -> $obj . "</td>");
				$text_count++;
				break;
			case 2:
				$obj = t("int_value_" . $menu_count);
				print t("<td>" . $measure_title[options][$data_res -> $obj] . "</td>");
				$menu_count++;
				break;
			}
		}
		print t("</tr>");
		$count++;
	}
	print t ("</table>");
	}
}
