<?php
// $Id: pi_datalogger.install, 2010/04/15 MCP Exp $

/**
 * hook_install() - nothing really to do here as this is an extension to pi_data
 */
 
function pi_datalogger_install() {
	variable_set('og_content_type_usage_pi_datalogger', 'group_post'); 
}

/**
 * hook_uninstall() - nothing really to do here as this is an extension to pi_data
 */
function pi_datalogger_uninstall() {
	variable_del('og_content_type_usage_pi_datalogger'); 
}
