<?php
// $Id: pi_feeders_conclusion.module,v 1.0 2009/12/01 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_feeders_conclusion" node type
 */


/**
 * Implementation of hook_node_info().
 */

function pi_feeders_conclusion_node_info() {

    return array(
    'pi_feeders_conclusion' => array(
    'name' => t('School bird feeders experiment conclusions'), // Required.
    'module' => 'pi_feeders_conclusion',  // Required.
    'description' => t('School bird feeders experiment conclusions'), // Required.
    'has_title' => TRUE,
    'title_label' => t('School bird feeders experiment conclusions'),
    'has_body' => FALSE,
    'body_label' => t('School bird feeders experiment conclusions'),
    'locked' => TRUE)
    );

}


//hide node revisions box - this is a node type often set to keep revisions
//if form alter not included then user sees the log message box
function pi_feeders_conclusion_form_alter(&$form, $form_state, $form_id) {
    global $user; // Bring $user object into scope if displaying shall depend on userid or role
    #if ( $user->uid != 1 ) // 0 -> Anonymous, 1 -> SuperAdmin, 2+ -> Authenticated users
    if ( !in_array('USER ROLE NAME', $user->roles) ) // Check for role (using role name)
    {
    // add class 'hideme' to elements which shall be hidden
        $form['revision_information']['#attributes'] = array('class' => 'hideme'); // Revision information
    // This class has been added to the CSS file:
    //  .hideme { display: none; }
    }
}

/**
 * Implementation of hook_perm().
 */

function pi_feeders_conclusion_perm() {
    return array('create pi_feeders_conclusion content', 'edit pi_feeders_conclusion');
}

/**
 * Implementation of hook_access().
 */
function pi_feeders_conclusion_access($op, $node) {
    global $user;
    $details = get_inquiry_details_from_current_path();

    if ($op == 'create') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'add');
    //return (user_access('create pi_feeders_conclusion'));
    }

    if ($op == 'update' || $op == 'delete') {
        return check_node_function_of_activity ($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
    //return (user_access('edit own pi_feeders_conclusion'));
    }
}

/**
 * Implementation of hook_form().
 */

function pi_feeders_conclusion_form(&$node) {

// Get metadata for this node type
// (we use it for labeling title and body fields).
// We defined this in pi_feeders_conclusion_node_info().
    $type = node_get_types('type', $node);
    global $user;

    $node_details = get_inquiry_details_from_current_path();
    if (is_numeric($node_details->activity_id)) {
        $current_activity = load_activity($node_details->activity_id);
    }

    if ($current_activity->name) {
        drupal_set_title(t($current_activity->name));
    }

    $form['title'] = array(
        '#type' => 'hidden',
        '#title' => check_plain($type->title_label),
        '#required' => FALSE,
        '#default_value' => check_plain($type->title_label),
        '#weight' => -7
    );

    $form['h_att'] = array(
        '#type' => 'textfield',
        '#title' => t('What did we learn from the observation of habitats at Attenborough?'),
	'#required' => FALSE,
	'#default_value' =>check_plain($node->h_att),
        '#weight' => -6
    );
    
        $form['n_att'] = array(
        '#type' => 'textfield',
        '#title' => t('What did we learn from noise mapping at Attenborough?'),
	'#required' => FALSE,
	'#default_value' =>check_plain($node->n_att),
        '#weight' => -5
    );
    
        $form['h_school'] = array(
        '#type' => 'textfield',
        '#title' => t('What did we learn from the observation of habitats at school?'),
	'#required' => FALSE,
	'#default_value' =>check_plain($node->h_school),
        '#weight' => -4
    );
    
            $form['n_school'] = array(
        '#type' => 'textfield',
        '#title' => t('What did we learn from the noise data at school?'),
	'#required' => FALSE,
	'#default_value' =>check_plain($node->n_school),
        '#weight' => -3
    );
    
            $form['n_garden'] = array(
        '#type' => 'textfield',
        '#title' => t('What did we learn from the noise data from a garden?'),
	'#required' => FALSE,
	'#default_value' =>check_plain($node->n_garden),
        '#weight' => -2
    );

    $prefix = "";

    if(arg(2) == 'edit') {
        $link = build_link('node', $node->nid, 'view', $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

        switch ($current_activity->destination) {
            case "self":
                $destination = "";
                break;
            case "phase":
                $destination = t("destination=" . build_link("phase", $node_details->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id,$node_details->activity_id));
                break;
            default:
                $destination = t("destination=" . build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id));
                break;
        }

        $prefix .= '<p>';
        $prefix .= l(t('View'), $link,  array('html' => true, 'query' => $destination));
        $prefix .= '</p>';
    }

/*
    if ($current_activity->description) {
    	$prefix .= "<p>" . t($current_activity->description) . "</p>";
    }
    else {
    	$prefix .= "<p>What did we learn from the different studies we did?</p>";
    }
*/

    $form['#prefix'] = $prefix;

    return $form;

}

/**
 * Implementation of hook_insert().
 */


function pi_feeders_conclusion_insert($node) {
    db_query("INSERT INTO {pi_feeders_conclusion} (nid, vid, h_att, n_att, h_school, n_school, n_garden) VALUES ('%d', '%d', '%s', '%s', '%s', '%s', '%s')",
        $node->nid, $node->vid, $node->h_att, $node->n_att, $node->h_school, $node->n_school, $node->n_garden);
}

/**
 * Implementation of hook_update().
 */

function pi_feeders_conclusion_update($node) {
    if ($node->revision) {
        pi_feeders_conclusion_insert($node);
    }

    else {
        db_query("UPDATE {pi_feeders_conclusion} SET h_att = '%s', n_att = '%s', h_school = '%s', n_school = '%s', n_garden = '%s' WHERE vid = %d", $node->h_att, $node->n_att, $node->h_school, $node->n_school, $node->n_garden, $node->vid);
    }
}

/**
 * Implementation of hook_delete().
 */

function pi_feeders_conclusion_delete(&$node) {
// Delete the related information we were saving for this node.
    db_query('DELETE FROM {pi_feeders_conclusion} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */

function pi_feeders_conclusion_load($node) {
    return db_fetch_object(db_query('SELECT * FROM {pi_feeders_conclusion} WHERE vid = %d',
    $node->vid));
}

/**
 * Implementation of hook_view().
 */
function pi_feeders_conclusion_view($node, $teaser = FALSE, $page = FALSE) {
    if (!$teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);

        $node->content['pi_feeders_conclusion'] = array(
            '#value' => theme('pi_feeders_conclusion', $node),
            '#weight' => 2
        );

    }

    if ($teaser) {
    // Use Drupal's default node view.
        $node = node_prepare($node, $teaser);
    }

    return $node;
}

function pi_feeders_conclusion_theme() {
    return array(
    'pi_feeders_conclusion' => array(
    'arguments' => array('node'),
    ),
    );
}

function theme_pi_feeders_conclusion($node) {

    $output = '<p><strong>What did we learn from the observation of habitats at Attenborough?</strong> ' . check_plain($node->h_att). '</p>';
    $output .= '<p><strong>What did we learn from noise mapping at Attenborough?</strong> ' . check_plain($node->n_att). '</p>';
    $output .= '<p><strong>What did we learn from the observation of habitats at school?</strong> ' . check_plain($node->h_school). '</p>';
        $output .= '<p><strong>What did we learn from the noise data at school? </strong> ' . check_plain($node->n_school). '</p>';
	    $output .= '<p><strong>What did we learn from the noise data from a garden</strong> ' . check_plain($node->n_garden). '</p>';


    return $output;
}
