<?php


/**
 * 
 * Registers an activity type in the authoring tool so that it ca be ofered 
 * to designers. Modules registering an activity must implement a number of
 * nQuire hooks:
 * 
 *  - [module]_nquire_creator_activity_[type]_form($activity, $design, &$form)
 *  - [module]_nquire_creator_activity_[type]_form_process($activity, $design, $data_values)
 * 
 * @param type $type The activity type being registered
 * @param type $module The module that manages the registered activity type
 */
function inquiry_available_activities_register($type, $module) {
  $activities = variable_get('nquire_creator_activity_types', array());
	$activities[$type] = $module;
	variable_set('nquire_creator_activity_types', $activities);
}

function inquiry_available_activities_forget($type) {
  $activities = variable_get('nquire_creator_activity_types', array());
	unset($activities[$type]);
	variable_set('nquire_creator_activity_types', $activities);
}

function inquiry_available_activities_types() {
  return variable_get('nquire_creator_activity_types', array());
}

function inquiry_available_activities_module_for_type($activity_type) {
  $types = inquiry_available_activities_types();
  return isset($types[$activity_type]) ? $types[$activity_type] : FALSE;
}

function inquiry_available_activities_invoke($nquire_creator_hook, $activity, &$a = NULL, &$b = NULL, &$c = NULL) {
  $module = inquiry_available_activities_module_for_type($activity->activity_type);
  if ($module) {
    $fname = "{$module}_nquire_creator_activity_{$activity->activity_type}_{$nquire_creator_hook}";
    if (function_exists($fname)) {
      return $fname($activity, $a, $b, $c);
    }
  }
  
  return FALSE;
}
