<?php
// $Id: ag.module,v 1.2 2009/06/24 09:17:48 ou_pm Exp $


/**
 * Implementation of hook_init().
 */
function pi_ag_navigation_init() {
}

/**
 * @file
 * Implements block for Activity Guide navigation.
 */
 
 /**  and n.uid = %d' $uid,
 * Implementation of hook_block().
 */
function pi_ag_navigation_block($op = 'list', $delta = 0, $edit = array())
{
	switch ($op)
	{
		case 'list':
			$blocks[0]['info'] = t('PI Activity Guide Navigation Menu');
			return $blocks;

		case 'view':
			global $user;
			$image_path = "images/";

			// Get node id, inquiry, stage, phase and action from the current url
			$node_details = get_inquiry_details_from_current_path();
			
			// Set default inquiry_id if not set
			if(!$node_details->inquiry_id)
			{
				$db_result = get_inquiries_of_user($user->uid);
				$latest_inquiry = db_fetch_object($db_result);
				$node_details->inquiry_id = $latest_inquiry->inquiry_id;
			}

			//Get the current stage of the inquiry for the user
			$current_stage = get_current_stage_of_inquiry_and_user($node_details->inquiry_id, $user->uid);	
			if (isset($current_stage->stage_id))
			{
			  $current_stage_id = $current_stage->stage_id;
			}
			else
			{
				$current_stage_id = '';
			};

			// Make a list of the phase_ids in the current stage
			$phases_of_current_stage = array();
			$current_stage_phases = get_phases_of_stage($node_details->inquiry_id, $current_stage_id);
			while ($phase_of_current_stage = db_fetch_object($current_stage_phases))
			{
				$phases_of_current_stage[] =  $phase_of_current_stage->phase_id;
			};
			
			
			//Generate navigation menu based on the phases in this stage, and the activities available
			$phase_menu_items = array();
			$phase_menu_item = array();

			$phases = get_phases_of_inquiry_and_user($node_details->inquiry_id, $user->uid);
			while ($phase = db_fetch_object($phases))
			{
				$loaded_phase = load_phase($phase->phase_id);
				$teacher_gid = check_teacher_phase_for_inquiry_phase_user($node_details->inquiry_id, $phase->phase_id, $user->uid);

				$phase_link = l($loaded_phase->name . teacher_only_flag($teacher_gid), build_link("phase", $phase->phase_id, "view", $node_details->inquiry_id, $node_details->stage_id, $phase->phase_id, $node_details->activity_id), array('html' => true));
				
				$activity_menu_items = array();

				//expand activities of the phase if it is current
				//if ($phase->phase_id == $node_details->phase_id)
				
				// Expand activities for all phases in this stage
				if (in_array($phase->phase_id, $phases_of_current_stage))
				{
					//$activities = get_activities_of_stage_phase_and_user(1, NULL, NULL, 1);
					$activities = get_activities_of_stage_phase_and_user($node_details->inquiry_id, NULL, $phase->phase_id, $user->uid);

					foreach($activities as $activity)
					{
						$activity_menu_items[] = build_activity_link($node_details->inquiry_id, $node_details->stage_id, $phase->phase_id, $activity->activity_id, $user->uid);
					};
				};
				
				//Change display class if phase is in this stage
				$phase_class = '';
				if (in_array($phase->phase_id, $phases_of_current_stage))
				{
					$phase_class = 'ag-phase-current';
				}
				else
				{
					$phase_class = 'ag-phase';
				}
				$phase_menu_items[] = array('data' => $phase_link, 'children' => $activity_menu_items, 'class' => $phase_class);
			}
			
			// Create home like "Inquiry Guide" at top of navigation list
			$home_link = build_home_link($node_details->inquiry_id, $node_details->stage_id, $node_details->phase_id, $node_details->activity_id);

			//Use the item_list template to create navigation menu
			$block_content = t(theme('item_list', $phase_menu_items, NULL, 'ul', array('class' => 'ag-phases')));
			// Now assing to to the view data 
			$block['content'] = "<div class='activity-guide'>" . $block_content . "</div>";
	
		return $block;
	}
}
