<?php




function devicecamera_designer_nquire_creator_tool_devicecamera_name() {
  return t('Device Camera');
}

/*********************
 * devicecamera_length measure *
 * *******************/

function devicecamera_designer_nquire_creator_measure_devicecamera_image_name() {
  return t('Device Camera Image capture');
}

function devicecamera_designer_nquire_creator_measure_devicecamera_image_description() {
  return t('This will allow participants to capture images with their device\'s camera (if available).');  
}

function devicecamera_designer_nquire_creator_measure_devicecamera_image_required_tool() {
  return 'devicecamera';
}

